### ISSUE TITLE
尝试编译失败:(

### ISSUE THREAD

**Issue by Falld0wn18** [angular/angular-cn#104]
你好，README.md上能否写明编译通过使用的node,npm和gulp版本？
gulp serve-and-sync-devguide 处报错，gulp版本为3.9.1
一开始是gulp不能识别gulpfile.js里ES6的语法
尝试使用babel-core babel-preset-es2015转义后，
var package = new Package('apiDocs', [require(path.resolve(TOOLS_PATH, 'api-builder/angular.io-package'))]);该行报错。。
还有就是“把Angular的源码取到本地”，这个放到哪里？后续步骤貌似没用到？

**Comment by rexebin** [comment]
我的mac： node：6.2.2, npm 3.10.8，编译没问题。gulp也没有抱怨说不能识别ES6。

PC： npm 3.10.5, node 5.12.0，也没有问题。

**Comment by Falld0wn18** [comment]
@rexebin  原先node的版本0.12.15编译失败，换为6.9.1版本后编译成功。感谢：)
