### ISSUE TITLE
angular-in-memory-web-api进行了破坏性更新

### ISSUE THREAD

**Issue by LastKing** [angular/angular-cn#105]
原来是这样
`
 'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',
`
现在是这样
`
 'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
`
并且删除了
`
  'angular-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      }
`

**Comment by rexebin** [comment]
你的意思是说英文版最近有这些更新？

**Comment by LastKing** [comment]
英文版本 暂时又没有 我没去看，但是如果按照现在0.1.5的版本，运行会出错。。。项目在http加入之后就跑不起来了。。。我只是提下而已。

**Comment by shijingoooo** [comment]
这问题纠结我两天了

**Comment by rexebin** [comment]
https://github.com/angular/angular.io/pull/2668/files 官方昨天解决了同样的问题。我拉过来。

**Comment by rexebin** [comment]
已经修复，稍后即发布。

谢谢！
