### ISSUE TITLE
【路由与导航】页面中两处翻译有误

### ISSUE THREAD

**Issue by SmokingIce** [angular/angular-cn#107]
在【高级文档】->【路由与导航】页面中两处有误：
1.
像 heroes.routing.ts 文件一样，我们也创建一个 crisis-center.routing.ts
We create a crisis-center-routing.module.ts file as we did the heroes-routing.module.ts file
文件名应该进行如下更改：
heroes.routing.ts ->heroes-routing.module.ts 
crisis-center.routing.ts->crisis-center-routing.module.ts

2.
在线例子 没有 高亮选中的行
The live example does highlight the selected row

没有->有

PS：认真学习Angular中，谢谢你们翻译的文档

**Comment by rexebin** [comment]
你们的纠错，对文档的质量有至关重要的作用。多谢贡献！
