### ISSUE TITLE
如何参与翻译工作？

### ISSUE THREAD

**Issue by todoubaba** [angular/angular-cn#108]
很高兴看到官方angular中文翻译，想知道如何参与其中。现在有翻译中有些不正确的地方，例如：

- stable of heroes 英雄围栏（stable of应为一群）
- Promise-based 基于承诺的（Promise不应翻译成中文）

**Comment by rexebin** [comment]
你好！你可以通过提issue或者pull request来为我们的文档做贡献。

如果想要加入我们文档组，我们需要进一步了解：
1. 是否有时间和精力参与
2. 是否能长期抗战，坚持到底

另外，如果有相关经验，那就更加合适了。

建议你先以提交Pull request的方式来帮助我们。我们可以将你加入到贡献者列表中。如果你有兴趣，我们可以进一步联系，讨论加入团队的可能性。

**Comment by asnowwolf** [comment]
支持加入，欢迎新鲜血液！已经发的这几个PR的质量很不错。

**Comment by rexebin** [comment]
欢迎加入！请问微信号是？

**Comment by todoubaba** [comment]
> 请问微信号是？

todoubaba
