### ISSUE TITLE
对于可能的angular2启动错误问题的解决

### ISSUE THREAD

**Issue by luyouxin84** [angular/angular-cn#11]
我的angular 1.0.0不能启动，后来搜索了网上大家的办法。
Windows环境下：
1.首先确认下 PATH环境变量有没有angular2里的node_module下的.bin目录，没有的话添加上去，然后在运行，看看如果还出错的话，错误信息也没有变化。（一般这个办法对应的ENOXXX这个错误）。
2.更改package.json文件

"scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
to

"scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },

非Windows系统。
要修改系统的watch数量。。
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

最后个方法，直接用lite-server（不能启动lite-server多半是PATH的问题）启动，angular2的模块是可以加载了，不过我不太确定这样会不会缺少一些其他模块。

**Comment by asnowwolf** [comment]
这是关于什么的问题？

**Comment by luyouxin84** [comment]
关于angular2启动报错的，google了2天总结的。。。jonepapa说这个算是少部分情况发生

**Comment by asnowwolf** [comment]
还是没看懂，能详细说一下来龙去脉吗？这是本文档的问题还是交流心得？如果是心得交流，请来我们的Angular中文社区QQ群：278252889

**Comment by luyouxin84** [comment]
有小部分人包括我，在angular2官网安装quickstart，那些启动文件都下载完了但是不能启动。。

**Comment by rexebin** [comment]
不能启动的原因可能有很多，可能是环境的问题，可能是设置的问题，也可能是版本的问题等等。如果你已经找到了问题的解决方案，你可以考虑详细写一下问题表象是什么，原因是什么，解决方案又有哪些，为何这些方案可以解决这个问题等。这样可以帮助有同样问题的网友。

如果你需要帮助，就需要告诉我们问题何在，如何再现问题，只有这样，我们才能帮助你。

**Comment by iloveyo123u1** [comment]
你用angular-cli  看看

**Comment by luyouxin84** [comment]
angular-cli貌似安装很麻烦，cnpm也没用。
我可以把angular-cli的beta14版（正式版的库）的全局文件传到群里，你们粘贴到全局目录就可以用了

**Comment by imwangxulong** [comment]
我从git上clone的代码，然后就启动不了，刚开始把e2e文件删了，可以启动了，后来按照快速起步添加了一些代码，又不行了，然后按照楼主说的，修改了"start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",可以了
