### ISSUE TITLE
中文版的依赖注入在线例子的一个文件转码出错了

### ISSUE THREAD

**Issue by e-cloud** [angular/angular-cn#116]
中文版：https://angular.io/resources/live-examples/dependency-injection/ts/plnkr.html
英文版：https://angular.cn/resources/live-examples/dependency-injection/ts/plnkr.html

打开中文版的`app/heroes/hero.service.provider.ts`，发现转码出问题了。

**Comment by asnowwolf** [comment]
目前的版本看着正常了，我先关闭啦，如果再发现就请打开它。
