### ISSUE TITLE
示例代码加载出错

### ISSUE THREAD

**Issue by liminjun** [angular/angular-cn#119]
https://angular.cn/docs/ts/latest/tutorial/toh-pt6.html 最下方文件汇总，除了第一个app.component.ts和hero-search.service.ts加载正确，其他的文件都加载出错了。
![image](https://cloud.githubusercontent.com/assets/966009/20244270/793fd7c8-a9b5-11e6-94bd-e7a2cb74df43.png)

![image](https://cloud.githubusercontent.com/assets/966009/20244271/7bd103ea-a9b5-11e6-9441-bd0c1d1f3fc6.png)

**Comment by rexebin** [comment]
非常感谢！
