### ISSUE TITLE
翻译的一点小建议

### ISSUE THREAD

**Issue by dreamapplehappy** [angular/angular-cn#12]
`AppComponent is the root of the application`，翻译成`AppComponent 是应用的根(基)`可能比`AppComponent 是应用的根目录`要好一点。
![AppComponent](http://angular.angular-china.org/66a05697-4410-4ac7-8699-9505d60d9e8b.jpg)

**Comment by rexebin** [comment]
“根组件”可能更合适。

**Comment by rexebin** [comment]
下次你可以考虑直接弄个Pull Request。谢谢！

**Comment by dreamapplehappy** [comment]
@rexebin 嗯 好哒

**Comment by rexebin** [comment]
已经改为：AppComponent是应用的根组件
