### ISSUE TITLE
一点关于“关于译者”部分的疑问

### ISSUE THREAD

**Issue by MiaoDX** [angular/angular-cn#124]
原本是来看看怎样能点击一下出英文的，感觉是个很好的想法，这在一些翻译社区比如 伯乐在线 或者是在更通用的场景下（个人博客中的外文翻译等）也可以借鉴一下。

然后，[关于译者](https://angular.cn/translate/cn/about.html) 部分人称代词满满是 “它”，难道是种“社区文化”？？ -.-

**Comment by rexebin** [comment]
可能在某次替换操作时考虑不周全，导致这个问题。多谢提出。
