### ISSUE TITLE
部分文档页面左侧菜单错误

### ISSUE THREAD

**Issue by LearnShare** [angular/angular-cn#127]
页面链接：  
<https://angular.cn/docs/ts/latest/api/core/index/ViewChild-var.html>  
<https://angular.cn/docs/ts/latest/api/core/index/ContentChild-var.html>

效果截图:   
![image](https://cloud.githubusercontent.com/assets/3265208/20588184/4291280c-b24e-11e6-9adf-4f68d5d455a7.png)

**Comment by grkin2002** [comment]
为什我上传不了

**Comment by todoubaba** [comment]
ViewChild-var.html 和 ContentChild-var.html 不存在，应该为
https://angular.cn/docs/ts/latest/api/core/index/ViewChild-decorator.html 和
https://angular.cn/docs/ts/latest/api/core/index/ContentChild-decorator.html

**Comment by LearnShare** [comment]
@todoubaba 

两个链接来自 https://angular.cn/docs/ts/latest/guide/template-syntax.html#!#one-way-in- 模板语法#单向输入 一节

看起来应该是中英文版本不对应造成的：
> 参见 API 参考手册中的 ViewChild 和 ContentChild。
>See the API reference for ViewChild and ContentChild.

翻译和原文的链接地址不同。
