### ISSUE TITLE
開發指南中的路由与导航的"里程碑 #2: “英雄”特性区"

### ISSUE THREAD

**Issue by gogobook** [angular/angular-cn#13]
1. 英雄应用的源码中的app.component中少了`providers:[HeroService]`
英文版也缺。
2. app.routes.ts中`import { CrisisListComponent } from './crisis-center/crisis-list.component';`
完成里程碑#2時，應該還沒有建危機中心的目錄。

**Comment by rexebin** [comment]
非常感谢你细心的观察。英文版原文存在这些问题。我来弄一个Pull request给原作者。如果你愿意，下次你也可以直接新建一个Pull Request。

**Comment by gogobook** [comment]
@rexebin 有2個源碼被改錯了，請確認。

1. app/app.routes.ts (v.2)
2. 最後的英雄应用的源码的`app.routes.ts
 
應該要使用ES6的 `...` 展開符。

**Comment by asnowwolf** [comment]
已改正，谢谢指出
