### ISSUE TITLE
《快速起步》最新版使用（npm start）有问题

### ISSUE THREAD

**Issue by imwangxulong** [angular/angular-cn#147]
cnpm start 无法启动，报错：
17 error Windows_NT 10.0.14393
18 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\im\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\im\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "start"
19 error node v6.9.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "tsc -w" "lite-server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-quickstart

后经研究：cnpm run lite 可以启动并且“Hello Angular”了

node只下载的 v6.9.1.exe直接安装的

**Comment by imwangxulong** [comment]
我是初学者
接上面的问题，后来我发现，删除e2e文件夹，就可以start了

**Comment by tanbowensg** [comment]
我也遇到了同样的问题。后来找到了解答：https://github.com/johnpapa/lite-server/issues/83。

try changing
"start": "tsc && concurrently "npm run tsc:w" "npm run lite" "
to:
"start": "concurrently "npm run tsc:w" "npm run lite" "
in your package.json file.

但这样改应该行为就不一样了吧。
