### ISSUE TITLE
选择文字的时候能不能不切换原文或者译文

### ISSUE THREAD

**Issue by bang88** [angular/angular-cn#15]
有强迫症。

点击的时候切换就可以了，选择的时候不切换。`var sel = getSelection().toString()`

![preview](https://cloud.githubusercontent.com/assets/433259/16572545/4725bce2-429c-11e6-948b-d53d9427aec1.gif)

**Comment by rexebin** [comment]
谢谢你的建议。已经实现本功能，更新后将不再在选择文字时切换原文。
