### ISSUE TITLE
angular.cn-高级文档-WEBPACK 简介中缺少代码

### ISSUE THREAD

**Issue by cyongk** [angular/angular-cn#177]
angular.cn-高级文档-WEBPACK 简介-试一试下缺少"src/index.html","src/main.ts","public/css/styles.css"

**Comment by rexebin** [comment]
我把这个 issue 转给官方。应该至少一个完整的可下载的应用可以下载。

**Comment by rexebin** [comment]
哦，英文版有。我修复一下。谢谢反馈。
