### ISSUE TITLE
高级文档—WEBPACK 简介

### ISSUE THREAD

**Issue by cn-fanfare** [angular/angular-cn#179]
用中文版的【WEBPACK 简介】package.json运行npm install后再运行npm start会报错。

用英文版的不会：https://angular.io/docs/ts/latest/guide/webpack.html

好像是包的问题。

希望你们能更新下中文版的【WEBPACK 简介】包实例。

**Comment by cn-fanfare** [comment]
错误是：cannot read property exclude of undefined.

来自node_modules\awesome-typescript-loader\src\instance.ts [266行]

code: compilerConfig.typingOptions.exclude = compilerConfig.typingOptions.exclude || [];

**Comment by asnowwolf** [comment]
已经更新到了最新版，请测试。
