### ISSUE TITLE
是不是这样翻译更恰当

### ISSUE THREAD

**Issue by wudingli** [angular/angular-cn#18]
QuickStart中的

>  Component 是一个 装饰器函数 ，它接受一个 元数据对象 作为参数。 通过给这个函数加上 @ 前缀，可以把这个函数加到组件类上，比如上面这个类。

> Component is a decorator function that takes a metadata object as argument. We apply this function to the component class by prefixing the function with the @ symbol and invoking it with a metadata object, just above the class.

是不是翻译成 “Component 是一个 装饰器函数 ，它接受一个 元数据对象 作为参数。通过给这个函数加上 @ 前缀，并在组件类声明的上方调用它，可以把这个函数加到组件类上”

**Comment by asnowwolf** [comment]
是的，可能是同步时漏掉了。
已改正。

**Comment by wudingli** [comment]
我的意思是 “just above the class” 应该是  “在这个类（组件类）上方”，而不是 “比如上面这个类”  吧。如果要强调 just 可以加上 紧挨着

**Comment by asnowwolf** [comment]
哦，对，理解错了，谢谢，已修正。
