### ISSUE TITLE
编译报错，缺文件：public/docs/_includes/_hover-card.jade

### ISSUE THREAD

**Issue by sasha6806** [angular/angular-cn#180]
使用编译命令`gulp build-compile --lang="ts|js"`时报错：
`[10:39:28] {
  "source": "Jade",
  "dest": "HTML",
  "filename": "D:\\Projects\\angular-cn\\public\\docs\\ts\\latest\\api\\forms\\index\\index.jade",
  "lineno": 9,
  "name": "Error",
  "message": "ENOENT: no such file or directory, open 'D:\\Projects\\angular-cn\\public\\docs\\_includes\\_hover-card.jade'",`
经查找代码库，public/docs/_includes/_hover-card.jade不存在。

**Comment by rexebin** [comment]
你编译的目的是？如果想在本地运行，你可以使用`gulp serve-and-sync`。
另外试试删除api目录下面所有的内容，然后再运行`build-compile`。

**Comment by asnowwolf** [comment]
问题还存在吗？我先关啦，如果仍然有问题请再重新打开。
