### ISSUE TITLE
开发指南中表单章节里的heroForm.reset()方法未定义。

### ISSUE THREAD

**Issue by leoskey** [angular/angular-cn#184]
你好，在 Angular For TypeScript “开发指南”中第8章“表单”有一个例子，描述如何按照预期正确重置表单。该按钮HTML文件的代码如下：
```
<button type="button" class="btn btn-default" (click)="newHero(); heroForm.reset()">New Hero</button>
```
在浏览器中，点击按钮会报如下错误：`Cannot read property 'reset' of undefined`。
我在该章节中找不到其声明，请问`heroForm.reset()`是如何而来，我该如何创建与使用？

**Comment by asnowwolf** [comment]
通过#变量（模板引用变量）引用的，这个表单中有类似这样的代码：`<form #heroForm="ngForm"....` 这里的heroForm就是这个heroForm变量。
