### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by ziofat** [angular/angular-cn#186]
![image](https://cloud.githubusercontent.com/assets/8521174/21749821/1435f6e2-d5e2-11e6-8f51-476bbb025d6d.png)
[主从结构](http://origin.angular.live/docs/ts/latest/tutorial/toh-pt2.html) 中关于为何要单独定义英雄数据的原因，划线处应当翻译为：
```我们本可以在这个组件类中定义英雄列表```
而非已经把英雄列表定义在组件类中。

**Comment by blackcater** [comment]
挤挤，中文版有个小错误。
![image](https://cloud.githubusercontent.com/assets/9465551/21925606/3234c350-d9b9-11e6-8460-5e980e97608f.png)

![anguar2-tutorial-user-input](https://angular.cn/docs/ts/latest/guide/user-input.html)

**Comment by TANXUELEI** [comment]
不好意思，也来借个楼。中文版翻译中有个小错误(不影响阅读，只是希望可以让中文版变得更完善)
![angular](https://cloud.githubusercontent.com/assets/25523650/22728396/9c4ab7cc-ee18-11e6-8dfa-bc54a6a24d57.jpg)

URL:https://angular.cn/docs/ts/latest/guide/npm-packages.html

**Comment by asnowwolf** [comment]
谢谢，都已经改正了，待发布。
