### ISSUE TITLE
webpack章节翻译有误

### ISSUE THREAD

**Issue by lizhonghui** [angular/angular-cn#189]
发现一处代码片段错误：[webpack.config.js](https://github.com/angular/angular-cn/blob/master/public/docs/_examples/webpack/ts-snippets/webpack.config.snippets.ts)

```
// #docregion loaders
loaders: [
  {
    test: /\.ts$/
    loaders: 'ts' // 此处有误，应为 'awesome-typescript-loader'
  },
  {
    test: /\.css$/
    loaders: 'style!css'
  }
]
```

另外，官方英文文档已经更新至 webpack2，中文文档还是老版的，如 module.loaders 改为 module.rules 等。现在 webpack 的 npm 默认已经是2.2以上了。

**Comment by asnowwolf** [comment]
正在同步，年后有大量修改，积压了很多。

**Comment by asnowwolf** [comment]
以同步到最新版，请检查

**Comment by lizhonghui** [comment]
赞 ~
