### ISSUE TITLE
文档好久没更新了

### ISSUE THREAD

**Issue by softboy99** [angular/angular-cn#190]
english version has been updated to 2.4，but chinese version still be 2.2

**Comment by asnowwolf** [comment]
正在同步。英文版主要是大量文字性和文档结构的更新，内容上的更新主要是cli和webpack相关的。现在有大量章节需要重新翻译，目前正在研究先上一个部分翻译的版本，也就是进行了文档结构调整的部分先保留英文，其它用中文。

**Comment by asnowwolf** [comment]
已同步到最新版，请检查

**Comment by softboy99** [comment]
英文官网的文档已经更新到4.0了，又该更新了。

**Comment by asnowwolf** [comment]
正在合并中，丧心病狂的几十个文件有冲突，每个文件中的冲突点也不计其数。更关键的问题是还没法多人并行来做。

**Comment by DongpoAlex** [comment]
辛苦了

**Comment by lqm229026** [comment]
难怪我跟着中文版tutorial学习在运行中会报错，对比了一下英文版的文档，发现代码有出入。估计是中文版文档还是2.x版本的吧。

**Comment by asnowwolf** [comment]
或者有git高手能给支个招不？看看怎么才能并行合并
