### ISSUE TITLE
Webpack Chinese documentation inconsistent with English

### ISSUE THREAD

**Issue by xuanshenbo** [angular/angular-cn#191]
For example, in the [Chinese version](https://angular.cn/docs/ts/latest/guide/webpack.html), the 加载器(Loader) part, in the code snippet (webpack.config.js (two entries)) the first keyword is "loaders". However in the English version it is "rules".

Is this a version problem?

Cheers

**Comment by lizhonghui** [comment]
yeah, the Chinese docs is outdate, which is based on webpack 1. the English docs have been upgraded to webpack 2. It is recommended to use `rules` instead of `loaders` in webpack 2.

**Comment by asnowwolf** [comment]
正在同步。英文版主要是大量文字性和文档结构的更新，内容上的更新主要是cli和webpack相关的。现在有大量章节需要重新翻译，目前正在研究先上一个部分翻译的版本，也就是进行了文档结构调整的部分先保留英文，其它用中文。

**Comment by asnowwolf** [comment]
已同步到最新版，请检查
