### ISSUE TITLE
如何访问英文版文档？

### ISSUE THREAD

**Issue by xaclincoln** [angular/angular-cn#192]
打开浏览器，输入https://angluar.io后url会自动变为angular.cn，点击网站底部的英文版链接，仍然会跳转到angular.cn，现在的问题是无法跳转到原始的英文链接。

**Comment by asnowwolf** [comment]
找了两个人测试，没能重新此问题，是否你本地环境设置过dns之类的？或者清了缓存或换个浏览器再看看。

**Comment by asnowwolf** [comment]
哦，你的域名拼错了，应该是 <https://angular.io>。你在这里点击跳转看看。
