### ISSUE TITLE
大家都散了 老实看英文版吧

### ISSUE THREAD

**Issue by fangqifan** [angular/angular-cn#195]
已经好久没更了 看样子也不确定以后会不会继续维护了
初次接触的新手还是上英文网站上看教程吧,按照中文教程使用官方提供的quickstart模板操作是跑不通的。因为quickstart模板是新的但是中文版没有更新。

**Comment by asnowwolf** [comment]
会继续维护的。过年期间积累了很多文字性和结构性更新，很多章节需要重新翻译，权宜之计是先把变化太大的部分保持英文，尽快上线，剩下的慢慢翻译。

**Comment by asnowwolf** [comment]
已同步到最新版，请检查。

**Comment by jin-xinchen** [comment]
建议删了此贴， 说风凉话不要紧， 太污染眼睛了！

**Comment by asnowwolf** [comment]
哈哈，没关系。他说的也没错，前一阵儿确实没怎么维护这里，有很多原因，不过已经基本上都解决了。等他自己验证后关闭吧。
