### ISSUE TITLE
中文版文章内自动生成的标题id不太合理，不利于外部索引

### ISSUE THREAD

**Issue by e-cloud** [angular/angular-cn#198]
如题，应该复制英文版对应标题的id。

（推荐）或者直接采用原标题的id，而原标题采用该id的副本形式。因为如果从英文版切换过来的话，其实直接替换替换`io`根域名为`cn`是很方便的。但是由于中文版对应的标题id是属于隐藏的英文标题的，浏览器不会自动跳转到隐藏元素的。

**Comment by asnowwolf** [comment]
已解决，请验证。
