### ISSUE TITLE
网站出错了，导致文档内容都不显示

### ISSUE THREAD

**Issue by xlushi** [angular/angular-cn#199]
![image](https://cloud.githubusercontent.com/assets/20568839/23542209/c488251a-0026-11e7-8369-9e1b7470bfe3.png)
![image](https://cloud.githubusercontent.com/assets/20568839/23542225/e46fb302-0026-11e7-8e52-92f5eba4d4e7.png)

**Comment by asnowwolf** [comment]
我这里无法重现，可能是刚才在更新cdn导致的，再刷新一下试试。

**Comment by xlushi** [comment]
哦，我们升级了谷歌浏览器到56，现在可以看了。经测试：IE11\搜狗\谷歌50\edge均不能正常显示内容。

**Comment by asnowwolf** [comment]
看来是兼容性问题，已解决，正在布cdn，请半小时后验证
