### ISSUE TITLE
资源路径如何切换到相对路径？

### ISSUE THREAD

**Issue by droid-Q** [angular/angular-cn#20]
因为我这边有多个站点。

**Comment by droid-Q** [comment]
我用chrome resource override plugin 暂时解决了问题。

**Comment by asnowwolf** [comment]
不太明白你的意思，不过我一般都是使用webpack的loader来解决此问题，参见我修改过的<https://github.com/asnowwolf/angular2-webpack-starter>

**Comment by droid-Q** [comment]
@asnowwolf  我大概的意思是我本机上用的是apache ，localhost下有多个静态站点，现在生成的www下的文件中调用的js目录都是根目录“/resources/。。。。”，导致找不到静态文件了，现在我用chrome插件去解决了。
