### ISSUE TITLE
更好的翻译措辞

### ISSUE THREAD

**Issue by qqiang00** [angular/angular-cn#204]
在网页：https://angular.cn/docs/ts/latest/tutorial/toh-pt2.html 中有一段这样的原文：

We could have defined the heroes list here in this component class. But we know that ultimately we’ll get the heroes from a data service. Because we know where we are heading, it makes sense to separate the hero data from the class implementation from the start.

原翻译：我们本该在这个组件类中定义英雄列表。 但显然，我们最终还是得从一个数据服务中获取这些英雄。 正因如此，一开始就应该把英雄数据隔离到一个类中来实现。
could have defined 最好翻译为“本可以”。 ultimately we'll是将来时，表明我们的目标
建议翻译为：我们本可以在这个组件类中定义英雄列表。不过我们知道我们的终极目标是将来从数据服务中获取这些英雄数据。因此，这里我们有意把英雄数据从组件类的实现独立出来。

**Comment by asnowwolf** [comment]
译作“我们确实可以...，但显然...”句式如何？

**Comment by asnowwolf** [comment]
译作：
```
    我们固然可以在这个组件类中定义英雄列表，但显然，最终我们还是得从一个数据服务中获取这些英雄。
    因此，不如索性一开始就把英雄数据隔离到一个类中来实现。
```
