### ISSUE TITLE
译文中关于目录漏了”/src“

### ISSUE THREAD

**Issue by jin-xinchen** [angular/angular-cn#209]
首先还是要说声，感谢！ 谢谢翻译者和组织者， 我阅读理解中文的效率还是比英文要高的多，此项目对我很有用。再次谢谢参与者！感谢！
URL: https://angular.cn/docs/ts/latest/guide/style-guide.html
译文：坚持在应用的根目录创建一个 Angular 模块（例如 **/app**）。
原文：Do create an Angular module in the app's root folder (e.g., in **/src/app**).
建议：坚持在应用的根目录创建一个 Angular 模块（例如 在目录 **/src/app**里）。
![image](https://cloud.githubusercontent.com/assets/22156525/23734570/dfb65d9a-044d-11e7-8ece-549027bc52e1.png)

**Comment by asnowwolf** [comment]
很细心啊！多谢指出，已经改正。
