### ISSUE TITLE
Angular 2 for Javascript 还没翻译吗？

### ISSUE THREAD

**Issue by titancat** [angular/angular-cn#21]
我访问[angular.cn](https://angular.cn/docs/js/latest/quickstart.html)的时候，发现 `Angular 2 for Javascript` 是显示英文，但是 `Angular 2 for TypeScript` 和 `Angular 2 for Dart` 已经是中文了。是我打开方式不对吗？

![js](https://cloud.githubusercontent.com/assets/3294102/16723067/5b60fda8-477d-11e6-97ed-bd3ed518bdfb.png)

![ts](https://cloud.githubusercontent.com/assets/3294102/16723073/625c62b4-477d-11e6-8288-c3e2af844f8a.png)

**Comment by asnowwolf** [comment]
我们只是翻译了TypeScript的，dart版其实是同一套代码用不同选项编译的结果。JavaScript目前我们没有投入精力，因为ES5写起来太繁琐了。我建议你也使用TypeScript，这是很值得去投资的语言，有着光明的未来。

**Comment by titancat** [comment]
@asnowwolf 万一 es6 和 ts 未来特性冲突了呢？
