### ISSUE TITLE
Single-use翻译为“单一用途”或“专一用途”比“只用一次”更贴切。

### ISSUE THREAD

**Issue by jin-xinchen** [angular/angular-cn#210]
URL:https://angular.cn/docs/ts/latest/guide/style-guide.html
建议：Single-use（或 single use）翻译为“单一用途”或“专一用途”比“只用一次”更贴切。实际中single-use classes在项目中会被多次使用的。
（如果我的名字jin-xinchen可以出现在https://angular.cn/translate/cn/about.html的鸣谢列表中，我会非常荣欣！（-。-））
截图如下：
![image](https://cloud.githubusercontent.com/assets/22156525/23828218/1ee38db0-0699-11e7-948d-59325605896a.png)

**Comment by asnowwolf** [comment]
加了。
single-use在这种上下文中应该就是指一次性的，单一用途在原文中是“singular purpose”。
single-use是指它不会被多个模块使用，也就是说没有复用价值，而单一用途通常是指符合SRP（单一职责原则），Angular框架中大多数类都是单一职责的。

**Comment by jin-xinchen** [comment]
不愧为雪狼, 你理解的深透。
