### ISSUE TITLE
没有生成www文件夹呢

### ISSUE THREAD

**Issue by guoguogis** [angular/angular-cn#211]
如何生成www文件夹及静态网站内容？

**Comment by asnowwolf** [comment]
`gulp build-compile --lang="(ts|js)"`

**Comment by cyongk** [comment]
使用gulp build-compile --lang="(ts|js)"还是不能生成www文件

**Comment by guoguogis** [comment]
public文件夹中只有*.jade文件，并没有www文件夹
![image](https://cloud.githubusercontent.com/assets/3822970/24100559/b1414626-0daf-11e7-9e29-98ede1cc992a.png)

**Comment by qingyejiazhu** [comment]
我打包出来了

**Comment by guoguogis** [comment]
单独运行：gulp harp-compile 可以生成www文件夹

**Comment by asnowwolf** [comment]
如果没有问题就关了吧。
