### ISSUE TITLE
教程的HTTP章节翻译不完整

### ISSUE THREAD

**Issue by cyongk** [angular/angular-cn#218]
教程的HTTP章下Get hero by id、getHeroes API 没变、可观察对象 (Observable) -按名搜索、导入 RxJS 操作符等节翻译不完整。

**Comment by DongpoAlex** [comment]
作者貌似不更新了

**Comment by cyongk** [comment]
好久没有人回复了，也没有人修改

**Comment by asnowwolf** [comment]
有几个章节原作者改动太大，现在精力不够，因此优先同步到最新版，冲突的部分直接采纳修改过的英文。同时，欢迎社区参与翻译，提交PR。

**Comment by asnowwolf** [comment]
已翻译完
