### ISSUE TITLE
笔误：DashbaordComponent

### ISSUE THREAD

**Issue by xieziyu** [angular/angular-cn#219]
url: [https://www.angular.cn/docs/ts/latest/guide/testing.html](https://www.angular.cn/docs/ts/latest/guide/testing.html#!#component-inside-test-host)

译文：它同时声明了**DashbaordComponent**和TestHostComponent。
原文：It declares both the **DashboardHeroComponent** and the TestHostComponent.
笔误：DashbaordComponent 应改成 DashboardHeroComponent

追加：另外还有其他一些地方的DashbaordComponent 应改成：DashboardComponent

![20170320175109](https://cloud.githubusercontent.com/assets/6669841/24095000/1b37a080-0d96-11e7-813b-ef65399613ad.png)

![20170320175607](https://cloud.githubusercontent.com/assets/6669841/24095107/85c9329c-0d96-11e7-8cc9-43f942e5686f.png)

**Comment by asnowwolf** [comment]
已改正
