### ISSUE TITLE
高级文档部分章节翻译不完整或者没有翻译

### ISSUE THREAD

**Issue by cyongk** [angular/angular-cn#225]
翻译不完整：路由与导航、测试等，没有翻译：DEPLOYMENT、REACTIVE FORMS、ANGULAR统一平台（UNIVERSAL）。希望翻译组能及时关注，谢谢伟大angula中文翻译组。

**Comment by asnowwolf** [comment]
这些是新增章节或大幅改动的章节，因此没有足够精力同步，欢迎提交PR。

**Comment by asnowwolf** [comment]
路由与导航翻译完了，请验证，测试正在翻译。universal得等英文版定稿之后才能翻译，现在他们还在大幅修改。

**Comment by asnowwolf** [comment]
哦，测试也已经翻译完了，请验证。

**Comment by asnowwolf** [comment]
响应式表单已经翻译完了，请帮忙校对，谢谢。
只剩下Universal得等一阵儿，英文版稳定了再翻译。
