### ISSUE TITLE
老是编译报错

### ISSUE THREAD

**Issue by popingblink** [angular/angular-cn#226]
在执行gulp build-compile --lang="(ts|js))"时
[20:55:55] npm ERR!
[20:55:55]  Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\li\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "harp" "--" "compile" "." "www"
[20:55:09] Harp site recompile: skipping recompilation of API docs for [dart]
[20:55:09] API docs will be copied from existing www folder (if they exist).
[20:55:09] Rename: mv www www-backup
[20:55:09] running harp compile...
[20:55:09] renameIfExistsSync cannot rename, path not found: public/docs/dart/latest/api
[20:55:09] running: npm run harp -- compile . www
[20:55:10]
> angular.io@0.0.0 harp C:\Users\li\Desktop\angular2\angular-cn\angular-cn
> harp "compile" "." "www"

**Comment by asnowwolf** [comment]
我没Windows环境，如果你有linux或mac或ubuntu on windows或cgywin环境的话编译下试试？

**Comment by njustyangkai** [comment]
@asnowwolf 我在mac和ubuntu编译都有同样的报错，帮看下啊，详见我的issue。

**Comment by sunwe** [comment]
@njustyangkai 从某个版本开始就一直编译失败，不清楚是哪的问题。关键问题lang不管是选择ts还是js或者ts|js，都会要编译docs/dart的部分。而dart下又没有实际内容，所以就报错了

**Comment by njustyangkai** [comment]
@sunwe 你那里有什么解决方法吗？

**Comment by sunwe** [comment]
@njustyangkai 还没找到解决办法 尝试修改过gulpfile.js一直没成功 功力太低。

**Comment by asnowwolf** [comment]
感觉和环境问题关联很大，如果你们只是要部署的话，我可以先编译打包一个传给你们，本地编译的问题你们回头再查。如何？

**Comment by sunwe** [comment]
@asnowwolf  非常谢谢，我的目的就是做个离线手册，查阅方便，那就受累发个包吧

**Comment by njustyangkai** [comment]
@asnowwolf 好的，我的目的也是做个离线手册，方便的话，发到我邮箱吧，谢谢！
njustyangkai@126.com

**Comment by asnowwolf** [comment]
@sunwe 也留个邮箱吧。回头我编译好就发给你。

**Comment by sunwe** [comment]
@asnowwolf  thx，我邮箱 sunwe@qq.com

**Comment by asnowwolf** [comment]
给你们发了。
另外，也上传到了 https://github.com/ng-nice/angular.cn-prebuilt 库中。

**Comment by yutiny** [comment]
本地编译同样碰到问题，编译中npm run harp -- compile . www 这条指令报错。
直接下了prebuilt，prebuilt会随着这个项目更新么？

**Comment by asnowwolf** [comment]
现在还没有，不过后面有空了我会做到CI中去，就可以自动更新了。
不过可以放心用，现在angular.io
库官方已经停止更新了，因为官方出了新界面的文档。不过主要是程序调整，文档内容上没什么变化，我需要先花点时间把它迁移到新版本。

2017-06-25 9:23 GMT+08:00 Yu Ting <notifications@github.com>:

**Comment by asnowwolf** [comment]
可以到 https://github.com/ng-nice/angular.cn-prebuilt 获取预编译版本。

**Comment by sunwe** [comment]
@asnowwolf 谢啦，有心了。aio分支我也编译通过了，以后更新prebuilt就可以省心不自己编译了。
