### ISSUE TITLE
教程-主从结构-文档不完整

### ISSUE THREAD

**Issue by burningice529** [angular/angular-cn#227]
https://www.angular.cn/docs/ts/latest/tutorial/toh-pt2.html

这一章节任务如下：
我们的《英雄指南》现在显示一个可选英雄的列表
我们可以选择英雄，并显示这个英雄的详情
我们学会了如何在组件模板中使用内置的ngIf和ngFor指令

但是文档上第二个任务缺失，ngIf的用法没有出现过

**Comment by asnowwolf** [comment]
编译问题，已改正。

**Comment by asnowwolf** [comment]
我先关闭了，验证后如果仍然有问题请重新打开或开新的issue
