### ISSUE TITLE
Angular.cn是按广电总局标准翻译的吗，有些地方翻译了反而会影响理解的

### ISSUE THREAD

**Issue by avastms** [angular/angular-cn#23]
到时候文档出了偏差，你们是要负责任的！

**Comment by rexebin** [comment]
请问广电总局的标准是什么？angular.cn是纯技术文档，我相信广电总局有更多重要的事做，不会考虑纯技术文档的翻译。请列出来哪些应该翻译哪些不应该，简单一句话说有些地方不应该翻译，对翻译质量没有任何帮助。

**Comment by asnowwolf** [comment]
关于一些英文是否需要翻译，我们也有过讨论，最终的结论是除了尽人皆知的词汇（比如web）、类名、变量名之外尽可能都翻译了。
这主要是考虑到我们的很多读者几乎是英语盲，中文更利于记忆，否则如果按照我自己的语言习惯，service都直接说的。
任何文章都不可能让每个人满意，我们只会为文档的信雅达负责，不会为了让某一个人满意而负责的。

**Comment by avastms** [comment]
我上午有点激动，实在不好意思。
我团队里新成员之前就在看angular.cn，效果并不太好，并且给其他人造成了困扰。
之前作为个人项目我无话可说，但现在成为官方我忍不住上来废话两句。
angular.cn过于直译了，希望你们不要拘泥于原文，真正用中文写作，信达雅不是现在这样的。

**Comment by rexebin** [comment]
请详细说明哪些翻译照成了困扰，我们可以有机会更正。我们无法根据几句笼统的几句话全部检查一遍，我们时间有限，请谅解。

**Comment by avastms** [comment]
Component,Service,Directive,等等都翻译之后形成的称谓习惯和其他人不一样，我们看英文文档的都直呼，导致问问题的时候问不到点子上。
还有就是看了半天看不懂，都是中文母语的人，看不懂中文文档，谁的锅。

**Comment by avastms** [comment]
当没有中文文档的时候，即便这个人英语不好，出于工作或者兴趣需要，他借助字典之类的工具，也是可以去读原文的，和我们这些能顺畅看英文文档的人产生的习惯，搜集的信息是非常近似的。
但有中文文档，尤其是官方中文文档之后，情况就不一样了，我是没办法阻止他们去读中文文档的，即便读中文文档实际上比查字典读英文文档效果更差，出于对英文的恐惧，他们也会义无反顾地去读中文文档的。
放下官方不官方的事情不说，起码让读文档的人能产生和译者一致的习惯吧

**Comment by rexebin** [comment]
英语和中文的语言习惯和表达方式很不一样。读惯英语的人一般免不了在中文中使用一些英语单词。严格意义上，这种方式更不好，因为每个人对单词的读音可能很不一样，交流起来不一定就和你说的那样流畅。尤其是英语不好的人。
我们翻译的时候也有考虑这个问题。但是，经过讨论，最终还是选择了翻译这些名词。只有一个特例，那就是保留对例子代码的直接引用。因为我们是翻译给中国母语且喜欢读中文的人群的。对于英文好的人群，最好的学习途径还是原文。对英语好的人来说，套用一下中文名称，照顾一下使用纯中文的战友比反过来适应要来得容易和有效。谁让Google不是中国本土企业，angular不是中国本土技术呢？
我明白你在团队中遇到这个问题。我觉得使用中文名称还是英文名称是团队内定的策略。可以全部统一用英文，也可以统一用中文。
我们有专门讲述词汇章节，可供你们参考。
如果我们统一修改，可能不能满足其他习惯使用中文名称的网友的需求。

Sent from Outlook for iPhone




On Wed, Jul 13, 2016 at 5:21 PM +0100, "Yanlong Wang" <notifications@github.com> wrote:












当没有中文文档的时候，即便这个人英语不好，出于工作或者兴趣需要，他借助字典之类的工具，也是可以去读原文的，和我们这些能顺畅看英文文档的人产生的习惯，搜集的信息是非常近似的。

但有中文文档，尤其是官方中文文档之后，情况就不一样了，我是没办法阻止他们去读中文文档的，即便读中文文档实际上比查字典读英文文档效果更差，出于对英文的恐惧，他们也会义无反顾地去读中文文档的。

放下官方不官方的事情不说，起码让读文档的人能产生和译者一致的习惯吧

**Comment by asnowwolf** [comment]
我在ThoughtWorks工作，如果按照我在我们公司的工作习惯，其实这份文档根本就不需要翻译了。

不同的团队情况不同，我们要优先满足的一定是基线水平，而所谓基线水平，就是高中毕业没考上大学的人，或者没过四级的大学生。我们ThoughtWorker的使命之一就是社会公正，而如果因为英语水平而让一些人无法追求梦想，显然是不公正的。

至于你说“看了汉语就不想学英语”的人，那是你多虑了。我相信如果你给他/她全资、脱产报个新东方，他/她会很愿意去学的。一方面是项目压力，一方面是生活压力，一方面是学英语，他/她为公司做出了这么多牺牲，凭什么还去指责他/她不上进呢？不同的阶层无法相互理解也算是正常的，但不要成为现代版的晋惠帝。

另外，为了激励大家学英语，我们的网站已经设计成了点任意译文都会显示出英语原文，我觉得应该够用了。搜索方面也不用担心，我们有一个庞大的社区建设计划，后面会出现大量优质的中文社区资源的，我希望有更多的人来进行中文资源的贡献。

**Comment by asnowwolf** [comment]
另外，你可以去跟MSDN Argue一下，现在他们的中文化程度也很高。MDN的很多页面也都有了中文版，甚至ietf都有了。

同时，我们还有计划把中文优秀文章翻译回英文甚至出英文版书籍，如果你真的属于流畅的使用英文的人，不妨加入到这个行列中，而不要盲目的为使用中文而自卑。
