### ISSUE TITLE
风格指南中，把组件当元素那里，组件写成了组建

### ISSUE THREAD

**Issue by nuonuoge** [angular/angular-cn#231]
**Please do not add issues or pull requests to this repo.** 
We are no longer making changes to documentation in this repository.
We will no longer process new issues or PRs and we will close them automatically.

**Please post new [issues](https://github.com/angular/angular/issues) and [pull requests](https://github.com/angular/angular/pulls) to the content folder in [https://github.com/angular/angular/tree/master/aio/content](https://github.com/angular/angular/tree/master/aio/content)**.

Be sure to prefix your issue/PR title with "**docs(aio):**"

**Comment by SangKa** [comment]
提 issues 前刚刚修正，[参见这个commit](https://github.com/angular/angular-cn/commit/54da8debbd0787204856321b11b3a83d92185020)
