### ISSUE TITLE
模版语法页面中的typo

### ISSUE THREAD

**Issue by Xwai** [angular/angular-cn#232]
url: https://www.angular.cn/docs/ts/latest/guide/template-syntax.html#!#template-expressions

章节：模版语法-模版表达式-表达式上下文

原文：典型的表达式上下文就是这个组件实例，它是各种绑定值的来源。 在下面的代码片段中，双花括号中的title和引号中的isUnchanged所引用的都是AppComponent**肿**的属性。

肿 -> 中

**Comment by asnowwolf** [comment]
已解决。
