### ISSUE TITLE
翻译小错误

### ISSUE THREAD

**Issue by looading** [angular/angular-cn#235]
![target](https://user-images.githubusercontent.com/9467452/28510447-142460e2-707b-11e7-8ed2-79a40b6e21a6.png)

path: 文档 -> 高级文档 -> 路由与导航 -> 路由守卫部分。 

翻译与原文有出入: 由下至上check完 CanDeactivate 和 CanActivateChild 守卫之后,应该不需要再次检查  CanActivateChild 守卫。

**Comment by asnowwolf** [comment]
已改正，请等待新版发布。
