### ISSUE TITLE
英文官网文档已经改版，中文网有什么计划？

### ISSUE THREAD

**Issue by Maroon1** [angular/angular-cn#238]
原 [angular.io](https://github.com/angular/angular.io) 仓库已经不再维护，文档全部迁往 [angular](https://github.com/angular/angular/tree/master/aio) 主仓库的aio目录中，文档格式也由原来的 **jade** 改为 **markdown**，目前是否打算更新为新版的网站。

**Comment by asnowwolf** [comment]
除了新增章节httpclient都翻译完了，已经在准备发布了。

**Comment by Maroon1** [comment]
httpclient一章有需要帮忙吗

**Comment by asnowwolf** [comment]
暂时不需要，正在翻译中，大约翻译了1/3了。

不过这次同步的规模很大，需要大家帮忙做测试。看到哪里没有翻译，或者翻译的有错误就随时来这里提issue或PR。多谢支持！

**Comment by asnowwolf** [comment]
已全部翻译完了，等复查完就上线。

**Comment by asnowwolf** [comment]
已发布。新版在 https://angular.cn ，旧版在 https://v2.angular.cn 。
