### ISSUE TITLE
<绑定到第二个属性> 第一段代码块出错

### ISSUE THREAD

**Issue by muxi2015** [angular/angular-cn#239]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://v2.angular.cn/docs/ts/latest/guide/attribute-directives.html

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
[图片](http://wx2.sinaimg.cn/mw690/9b5fc159ly1fiae8hkkroj20zg0gjtbh.jpg)

建议的修改方式（可选）：
**我只是一个正在读文档的小白,不知道有没有更好的方式将问题反馈给翻译组的成员.**
感谢您的翻译.

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
已改正，半小时后生效。建议看新的官网 angular.cn ，完全涵盖了以前的文档。

**Comment by muxi2015** [comment]
@asnowwolf 感谢,早上收到邮件就发现正常了,提个建议,斜体与正常的文字之间添加一个空格看起来似乎更舒服.
[默认](http://wx4.sinaimg.cn/mw690/9b5fc159ly1fiblbpulr8j20k502m3ys.jpg)
[加了空格](http://wx2.sinaimg.cn/mw690/9b5fc159ly1fiblbpexdwj20mt03w74l.jpg)
可以closed issues了.

**Comment by asnowwolf** [comment]
好，谢谢提议，我尝试一下。
