### ISSUE TITLE
申请加入！不知道有哪里可以帮忙的！

### ISSUE THREAD

**Issue by xinghalo** [angular/angular-cn#24]
之前使用过一段时间的angularjs，翻译了一小部分的文档。

可以[参考我的博客地址](http://www.cnblogs.com/xing901022/category/658522.html)

非常希望能在这个社区贡献出自己的一点微薄之力

**Comment by asnowwolf** [comment]
太好了！
我们现在百业待兴，有很多方面的事情要做，目前已经组织了一个团队翻译ng-book2，后面还会开始运营中文社区的官方公众号。
请先加我的微信asnowwolf，并注明自己的github id，等我喘口气把后面的事情梳理下再跟你讨论未来的具体事项。
