### ISSUE TITLE
gulp serve-and-sync-devguide 之后点击进入页面都会报错

### ISSUE THREAD

**Issue by Ray200304** [angular/angular-cn#241]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：http://localhost:3000/docs/ts/latest/quickstart.html

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
D:\angular-cn\public\docs\ts\latest\quickstart.jade
   1| block includes
   2|   include _util-fns
   3| 
 > 4| :marked
   5|   Angular applications are made up of _components_.
   6|     A _component_ is the combination of an HTML template and a component class that controls a portion of the screen. Here is an example of a component that displays a simple string:
   7|     
Harp v0.24.0  Documentation

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
已经更新了版本，以前的版本已不再更新。再看看是否还有这个问题。
