### ISSUE TITLE
about us page problems

### ISSUE THREAD

**Issue by linyang4** [angular/angular-cn#246]
出错的URL：https://angular.cn/translations/cn/about

错误的内容：
在 Github 上 <iframe src="./github-btn.html?user=angular&repo=angular-cn&type=watch&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="130" height="30"">我们 或 <iframe src="./github-btn.html?user=angular&repo=angular-cn&type=fork&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="130" height="30""> 我们

建议的修改方式（可选）：此处应为github的一个链接, 却显示了html标签

**Comment by asnowwolf** [comment]
已改正
