### ISSUE TITLE
这个翻译会让人误解吧

### ISSUE THREAD

**Issue by bluewaitor** [angular/angular-cn#248]
https://github.com/angular/angular-cn/blob/1340927e16fcfe8cce5696f678d727ccb5cb42f7/public/docs/ts/latest/guide/forms.jade#L345

应该是  如果组件、指令或管道属于`imports`数组中的某个module  吧

**Comment by asnowwolf** [comment]
这个属于错译，已改正。正确的译法是：

如果某个组件、指令或管道是属于`imports`中所导入的某个模块的，那就_不能再_把它再声明到本模块的`declarations`数组中。
如果它是你自己写的，并且确实属于当前模块，*才应该*把它声明在`declarations`数组中。
