### ISSUE TITLE
关于angular2 依赖注入的问题

### ISSUE THREAD

**Issue by liwenbing** [angular/angular-cn#25]
你好：
          我在中文官网中按照 Visual Studio 2015 中新建 angular2 quickstart 项目并架设到本地IIS，并能很好的运行，但在我添加其他组件并需要注入http组件时，则出现“_Make_ sure that all the parameters are decorated with Inject or have valid type annotations and that _'DemoService'_ is decorated with Injectable”错误，
         后来我尝试使用 npm start 编译并启动 quickstart 项目时，却能很好的运行。
         关于使用visual studio 编译typescript 和 npm 在注入方面有什么区别吗，或您有关于此问题的建议吗？

**Comment by rexebin** [comment]
能否共享你出错的项目，我们可以帮你看看，谢谢。

**Comment by asnowwolf** [comment]
如果自己解决了，请回复一下解决的办法，以便我们关闭它。谢谢！

**Comment by liwenbing** [comment]
升级了TypeScript的版本，但在Visual Studio 2015 中并没有使用最新的版本。 删除项目文件关于TypeScript的描述后正常
