### ISSUE TITLE
angular中文版本，特性描述——代码拆分翻译出错

### ISSUE THREAD

**Issue by zhouchangsheng** [angular/angular-cn#254]
在angular中文版本的特性介绍中，**代码拆分**[翻译](https://angular.cn/features)和[英文](https://angular.io/features)的意思不一致。

----------翻译原文-------

速度与性能

代码生成
Angular会把你的模板转换成代码，针对现代JavaScript虚拟机进行高度优化，轻松获得框架提供的高生产率，同时又能保留所有手写代码的优点。

统一平台
在服务端渲染应用的首屏，像只有HTML和CSS的页面那样几乎瞬间展现，支持node.js、.NET、PHP，以及其它服务器，为通过SEO来优化站点铺平了道路。

代码拆分
在服务端渲染应用的首屏，像只有HTML和CSS的页面那样几乎瞬间展现，支持node.js、.NET、PHP，以及其它服务器，为通过SEO来优化站点铺平了道路。

----------翻译原文-------

翻译还是不错的，感谢你们!使我能够快速学习angular~

我的github   [zhouchangsheng](https://github.com/zhouchangsheng)

**Comment by asnowwolf** [comment]
已改正。
