### ISSUE TITLE
aio版本部署问题

### ISSUE THREAD

**Issue by sunwe** [angular/angular-cn#259]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

aio新版本使用yarn包管理，但是安装最新的yarn后，执行yarn或yarn setup时，报本地node版本过高，只能是使用node version为 ">=6.9.5 <7.0.0"的版本，我本地都已经是8.2.1了。。。而实际最新版yarn-1.0.2要求的node只要高于5.7就行了。
同样，还报yarn自身版本过高，不能高于1.0.0。。。
有点无语，希望angular.io英文版官方能重视这个问题，换掉必须的低版本模块，考虑最大化的兼容。我英文不太好，借angular-cn贵地，请求angular-cn帮助提报下这个问题。

**Comment by asnowwolf** [comment]
你说的问题我会反应上去，但不清楚啥时候能解决。目前你可以先用nvm试试，它可以让你本地多版本并存。

**Comment by denney** [comment]
我也碰到部署问题了，也是醉了，到底有没有人解决
