### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by wangsai** [angular/angular-cn#26]
The license of angularjs code and documentation is : 

```
Powered by Google ©2010-2016. Code licensed under an MIT-style License. Documentation licensed under CC BY 4.0.
```

BUT, you have changed the license to [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.en) , it seems like you broke the original LICENSE.
Is this OK?

---

angularjs 的源码和文档分别遵循 MIT 和 [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) 协议，而你们翻译的文档却将协议修改为 [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.en)，这样做合适吗？

**Comment by asnowwolf** [comment]
有道理，以前我们是个人翻译作品，因此对译文部分加上了非商业限制，从协议本身来看是允许的。现在作为官方文档发布，加上NC确实不太合适，我们会商量一下再确定一种新的授权方式。
