### ISSUE TITLE
【改善】速查表部分没有汉化。

### ISSUE THREAD

**Issue by powerthink** [angular/angular-cn#260]
・问题的URL：   https://www.angular.cn/guide/cheatsheet
・问题的内容：速查表部分没有汉化。
・建议的修改方式：希望可以尽快汉化。因为速查表部分对于快速上手生产开发很重要！

※总体上翻译还是相当不错的，感谢你们的努力！使我们能够快速上手Angular2。

**Comment by asnowwolf** [comment]
汉化完毕。如果有细节错误可以提 PR 来修改。
