### ISSUE TITLE
明显的错别字

### ISSUE THREAD

**Issue by Wuitar** [angular/angular-cn#262]
出错的URL：https://angular.cn/tutorial/toh-pt3

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
错误的内容->src/app/app.component.html
只是文件类型错误，找到了这里https://github.com/angular/angular-cn/blob/aio/aio/content/tutorial/toh-pt3.md
结果发现这段代码不存在，英文版那边也是错的。
![image](https://user-images.githubusercontent.com/15797127/31110620-46ed650a-a843-11e7-90fd-89ab3d73efda.png)

建议的修改方式（可选）：
src/app/app.component.ts

**Comment by asnowwolf** [comment]
没看明白……能详细说明一下吗？看上下文这里应该就是引用的html文件啊。

**Comment by Wuitar** [comment]
引用的文件因该是 src/app/app.component.ts
代码中的HTML是放在.ts的template里的，不是在*.html里。

**Comment by asnowwolf** [comment]
哦，明白了，谢谢，我去改一下。

**Comment by asnowwolf** [comment]
哦，不对，这个就是html文件，因为这段引用的是本章后面部分的代码，而后面已经把模板单独拆出去了，所以这里的说法应该是对的。`app.component.html`这个文件确实不存在，因为它放在了一个名叫`app.component.1.html`的文件中。用这个文件名只是为了让大家看得明白一些。
