### ISSUE TITLE
架构概括中的锚链接错误

### ISSUE THREAD

**Issue by SkyStardust** [angular/angular-cn#264]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/guide/architecture

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

声明本模块中拥有的视图类。Angular 有三种视图类：组件、指令和管道。

组件，指令的链接未对应正确链接导致无法跳转

现链接
组件:https://angular.cn/guide/architecture#components
指令:https://angular.cn/guide/architecture#directives

建议的修改方式（可选）：

应更改为
组件:https://angular.cn/guide/architecture#组件
指令:https://angular.cn/guide/architecture#指令-directive

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by Wuitar** [comment]
我在墙外，两个链接都能打开。

**Comment by SkyStardust** [comment]
是锚链接无法正确跳转，不是打不开

**Comment by asnowwolf** [comment]
翻译程序的问题，已改正。
