### ISSUE TITLE
中文版页面模板语法内容格式问题

### ISSUE THREAD

**Issue by HNUHell** [angular/angular-cn#266]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/guide/template-syntax

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

当没有合适的宿主元素防止指令时，可用\<ng-container>](structural-directives.html#ngcontainer "对元素进行分组。
to use <ng-container> to group elements when there is no suitable host element for the directive.
如何写自己的结构型指令。
我们只能往一个元素上应用一个结构型指令。
本节是对常见结构型指令的简介：

NgIf - 根据条件把一个元素添加到DOM中或从DOM移除
NgIf - conditionally add or remove an element from the DOM
NgSwitch - a set of directives that switch among alternative views
NgSwitch - 一组指令，用于切换一组视图
NgForOf - repeat a template for each item in a list
NgForOf - 对列表中的每个条目重复套用同一个模板
NgForOf - repeat a template for each item in a list

截图：
![image](https://user-images.githubusercontent.com/30611276/31526633-a8a57454-affa-11e7-8aac-16e0c3926bb8.png)

建议的修改方式（可选）：修正链接，调整修复NgSwitch的展示问题

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
已改正。
