### ISSUE TITLE
动态组件加载器一章中的在线案例及下载范例资源丢失

### ISSUE THREAD

**Issue by nickChenyx** [angular/angular-cn#269]
出错的URL：
【资源404】https://angular.cn/generated/live-examples/cb-dynamic-component-loader/eplnkr.html
【这个页面的在线例子/案例下载都失败】https://angular.cn/guide/dynamic-component-loader

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

PAGE NOT FOUND
We're sorry. The page you are looking for cannot be found.

建议的修改方式（可选）：

添加新的资源链接

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

nickChenyx

感谢您的贡献。

**Comment by asnowwolf** [comment]
已改正。
