### ISSUE TITLE
快速教程 toh-pt6 部分 angular-in-memory-web-api 问题

### ISSUE THREAD

**Issue by rthel** [angular/angular-cn#272]
出错的URL：https://angular.cn/tutorial/toh-pt6#模拟web-api

#### 错误的内容：

```
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
```

这一行引入了一个`'angular-in-memory-web-api'`的模块，需要单独安装，新手很容易想到:
```
cnpm install angular-in-memory-web-api --save
```
但这么做导致无法通过`http.get('api/heroes')`获取数据，原因我查了一下，是版本的问题，2017年10月30日自动安装的版本号为`0.5.1`，教程使用的版本是`0.4.0`。

#### 建议的修改方式：

建议更新教程代码，或者在教程中备注下`angular-in-memory-web-api` 的版本

rthel

**Comment by asnowwolf** [comment]
已加备注。
