### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by wkylin** [angular/angular-cn#276]
出错的URL：
https://angular.cn/guide/router#routing-module

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
switchMap操作符也会取消以前未完成的在途请求。如果用户使用心得id再次导航到该路由，而HeroService仍在接受老id对应的英雄，那么switchMap就会抛弃老的请求，并返回这个新id的英雄信息。

建议的修改方式（可选）：心得 改为 新的

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
已改正。
