### ISSUE TITLE
英雄指南->教程->http这个章节获取不到数据

### ISSUE THREAD

**Issue by yuanchang2018** [angular/angular-cn#277]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://www.angular.cn/tutorial/toh-pt6

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
private heroesUrl = 'api/heroes';  // URL to web api
 
constructor(private http: Http) { }
 
getHeroes(): Promise<Hero[]> {
  return this.http.get(this.heroesUrl)
             .toPromise()
             .then(response => response.json().data as Hero[])
             .catch(this.handleError);
}
 
private handleError(error: any): Promise<any> {
  console.error('An error occurred', error); // for demo purposes only
  return Promise.reject(error.message || error);
}

建议的修改方式（可选）：
getHeroes(): Promise<Hero[]> {
  return this.http.get(this.heroesUrl)
             .toPromise()
             .then(response => response.json() as Hero[])
             .catch(this.handleError);
}
我用教程上的getHeroes()获取的数据一直为空，最后排查了一个小时，把response.json().data改成response.json()得到了数据。这个文件src/app/in-memory-data.service.ts里面的数据是直接拷贝英雄指南里面的内容的，这个数据源应该是没有问题的。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by yuanchang2018** [comment]
我项目的package.json
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.7",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
我在http这一章学习中，只要涉及.then(response => response.json().data as Hero[])，都会出现获取不到数据的问题，是因为我项目某个库的版本过高吗？请指教

**Comment by asnowwolf** [comment]
这一章已经重写了，请参照最新版再试试。
