### ISSUE TITLE
该升级angular5了，快点哦

### ISSUE THREAD

**Issue by liepeng328** [angular/angular-cn#280]
如题

感谢您的贡献。

**Comment by asnowwolf** [comment]
最近比较忙，明年一月份开始同步最新版

**Comment by arayte** [comment]
能否也出一个rebuilt版，windows源码编译一直失败。

**Comment by asnowwolf** [comment]
抱歉各位，最近在做一个复杂度较高的 Angular 项目，比较忙。可能要到2月份才能开始更新了。现在合并了一部分章节，等全部合并完才能提交。在目前的工作流下，合并工作很难找别人分担，所以只能尝试我自己来做了。

@arayte 可以，回头我先建个个人仓库存放它吧，如果此类需求比较多，我再申请在官方组下开 prebuilt 仓库。

**Comment by asnowwolf** [comment]
已经同步到 ng 6 beta-5 了。英文版完全重写了《英雄指南》教程，已经翻译完毕。高级文档部分有很多新增章节和大型改动还没有翻译。

**Comment by asnowwolf** [comment]
@arayte prebuilt 的版本暂时放在了 https://github.com/ng-nice/angular.cn-prebuilt 可以直接在你们的内网服务器部署了。

**Comment by arayte** [comment]
@asnowwolf  十分感谢！
