### ISSUE TITLE
网页右边的大纲导航

### ISSUE THREAD

**Issue by xp44mm** [angular/angular-cn#283]
出错的URL：
大部分网页，例如：
https://angular.cn/guide/displaying-data

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
网页右边的大纲导航，无法定位，比如点击【显示数据】后，浏览器导航到：
https://angular.cn/guide/displaying-data#%E6%98%BE%E7%A4%BA%E6%95%B0%E6%8D%AE
显然导航到了一个不存在的id上，所以网页并没有反应。

建议的修改方式（可选）：
应该是锚匹配的问题。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
已经改正。是中文标题的 id，现在只用英文标题的 id 了。
