### ISSUE TITLE
响应式表单demo中的一些小问题

### ISSUE THREAD

**Issue by HEHEMonster** [angular/angular-cn#284]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/guide/reactive-forms

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
响应式表单demo的文件名打错了
![image](https://user-images.githubusercontent.com/16699173/35027304-fa1e45fa-fb8a-11e7-822a-9a77bd0ceea4.png)

![image](https://user-images.githubusercontent.com/16699173/35027336-20c025d4-fb8b-11e7-85dd-f44bc7f10926.png)
![image](https://user-images.githubusercontent.com/16699173/35027354-375b091c-fb8b-11e7-841f-f6da9c39825f.png)

建议的修改方式（可选）：
Reactive Form Demo 中建议删除 hero-detail-6.component.html 与 hero-detail-7.component.html，因为根本没有使用这2个模板。我自己在模仿demo写代码的时候误以为 模板与组件文件是一一对应的，检查了许久自己的代码 结果却发现是 demo的组件文件应用了其他模板。也许这是我自己的不细心，但希望能修改一下这个问题，让大家阅读demo时能更顺畅一些，谢谢！

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
哦，这个属于原版文档的决定，我不太清楚其中的原因，回头我发个英文版 issue 给他们看看。
