### ISSUE TITLE
linkCanAcitvateChild,拼写错误

### ISSUE THREAD

**Issue by Eve-1995** [angular/angular-cn#285]
全局搜索下这个单词即可,错误非常细微,正确的拼写是linkCanActivateChild.
如需留名,请写Eve

**Comment by asnowwolf** [comment]
并没有发现这个单词，怀疑是以前的翻译程序的问题。现在还会出现吗？

**Comment by Eve-1995** [comment]
重新找了下,是存在的,路径是:核心知识→路由与导航→里程碑5:路由守卫→CanAcitvateChild：保护子路由,这里拼错了

**Comment by asnowwolf** [comment]
还是没有发现这个单词。刷新一下浏览器再看看，已经升级到6.0，并且更新了翻译程序。

**Comment by Eve-1995** [comment]
![qq 20180309155033](https://user-images.githubusercontent.com/30228406/37196411-9e8507b6-23b1-11e8-9953-89514306c5fd.png)

**Comment by Eve-1995** [comment]
![qq 20180309155033](https://user-images.githubusercontent.com/30228406/37196456-cd523fbe-23b1-11e8-9e6e-543f1b5ee112.png)

**Comment by asnowwolf** [comment]
哦，看到了，谢谢。赞！真细心！

我开始还以为是指多余的 link。

已改正，多谢。
已加鸣谢清单。
