### ISSUE TITLE
Reponse对象拼写错误

### ISSUE THREAD

**Issue by perry2008084** [angular/angular-cn#286]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/tutorial/toh-pt6

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
在 promise 的then()回调中，我们调用 HTTP 的Reponse对象的json方法，以提取出其中的数据。

建议的修改方式（可选）：
在 promise 的then()回调中，我们调用 HTTP 的Response对象的json方法，以提取出其中的数据。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by asnowwolf** [comment]
已解决。
