### ISSUE TITLE
文件拓展名翻译错误

### ISSUE THREAD

**Issue by zhoumaoqiang** [angular/angular-cn#290]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://www.angular.cn/tutorial/toh-pt0

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
原文修改应用标题这一节，为css的扩展名被翻译成ts扩展名（错误如下）
### 修改应用标题
...
app.component.ts— 组件的私有 CSS 样式。
app.component.css— the component's private CSS styles.

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

感谢您的贡献。

**Comment by ChristinaLy** [comment]
也发现了这个问题，发现已经提了issue了。上个图补充一下
![bug](https://user-images.githubusercontent.com/7933348/37701549-62c6a4c8-2d2a-11e8-8499-448c1e55f865.png)

**Comment by ChristinaLy** [comment]
Fix this in #292

**Comment by asnowwolf** [comment]
已合并PR，感谢
