### ISSUE TITLE
教程 6.服务 src/app/hero.service.ts (Observable imports)

### ISSUE THREAD

**Issue by marsrandy** [angular/angular-cn#293]
载入rxjs的Observable和of 与英文版的不同
会报错，没有 of

`import { Observable, of } from 'rxjs';`

应该是：
`import { Observable } from 'rxjs/Observable';`
`import { of } from 'rxjs/observable/of';`

**Comment by asnowwolf** [comment]
目前中文版本是 6.0 beta，英文版 5.2 stable，应该是 rxjs 改了最佳实践导致的。报的应该是个 lint 错误吧？你先手动改吧。从 tslint.json 中把 rxjs 去掉：

```
    "import-blacklist": [
      true,
      "rxjs",  // 删除它
      "rxjs/Rx"
    ],
```
