### ISSUE TITLE
教程 6.服务 中的代码错误

### ISSUE THREAD

**Issue by FAOfao931013** [angular/angular-cn#294]
#### 可观察对象版本的 HeroService 
其中的代码
`import { Observable, of } from 'rxjs';`
应该替换为
`import { Observable } from 'rxjs/Observable';`
`import { of } from 'rxjs/observable/of';`
不然运行会报错

**Comment by fenpho** [comment]
也可以这样写
import { Observable } from 'rxjs';

  getHeroes(): Observable<Hero[]> {
    return Observable.of(HEROES);
  }

**Comment by asnowwolf** [comment]
这是 6.0 的写法，由于优化器的提升以及 rxjs 库的改进，这种写法已经不再被反对使用了。你可以建个新工程试试看。
