### ISSUE TITLE
错别字:sometimes(文档翻译为'有事'了)

### ISSUE THREAD

**Issue by Eve-1995** [angular/angular-cn#295]
出错的URL：https://angular.cn/guide/http#%E7%9B%91%E5%90%AC%E8%BF%9B%E5%BA%A6%E4%BA%8B%E4%BB%B6

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
暂时不会PR....只能麻烦你们手动改了.

![default](https://user-images.githubusercontent.com/30228406/38418294-5d798ba6-39ce-11e8-8fab-9a4e5970c163.png)

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：之前已留过名

**Comment by asnowwolf** [comment]
已改正，多谢。
