### ISSUE TITLE
核心知识->模版与数据绑定->显示数据,翻译错误 angular不能翻译为"英雄"

### ISSUE THREAD

**Issue by a854363956** [angular/angular-cn#297]
在核心知识->模版与数据绑定->显示数据,中"In this page, you'll create a component with a list of heroes. You'll display the list of hero names and conditionally show a message below the list." 翻译成为"本章中，你将创建一个英雄列表组件。 你将显示英雄名字的列表，并根据条件在列表下方显示一条消息。" 能否将"英雄"替换成为angular或者直接翻译为列表组件?

**Comment by asnowwolf** [comment]
直译就是带有英雄列表的组件，中文写成“英雄列表组件”应该也没问题吧？

**Comment by asnowwolf** [comment]
我改成直译形式吧，简写也省不了几个字，还容易被误解。多谢。
