### ISSUE TITLE
管道章节其中一些还没翻译

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular-cn#31]
管道这章
https://angular.cn/docs/ts/latest/guide/pipes.html

其中这几段还没翻译：
Clearly some values benefit from a bit of massage. We soon discover that we desire many of the same transformations repeatedly, both within and across many applications. We almost think of them as styles. In fact, we'd like to apply them in our HTML templates as we do styles.

Angular reports an error if we neglect to list our custom pipe. We didn't list the DatePipe in our previous example because all Angular built-in pipes are pre-registered. Custom pipes must be registered manually.

If we try the 在线例子, we can probe its behavior by changing the value and the optional exponent in the template.

**Comment by Hongbo-Miao** [comment]
并且像这句话，不能像其他话点击可以折叠英文：

Introducing Angular pipes, a way to write display-value transformations that we can declare in our HTML! Try the 在线例子.

欢迎来到Angular“管道(Pipe)”的世界！我们可以把这种简单的“值-显示”转换器声明在HTML中。 试试在线例子。

**Comment by asnowwolf** [comment]
已解决。
