### ISSUE TITLE
英文显示不全

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular-cn#32]
https://angular.cn/docs/ts/latest/guide/router.html

> 为激活的 URL 显示应用组件。管理从一个组件到另一个组件的导航

这句话现在点开英文显示的是
> .the application component for the active URL.navigation from one component to the next.

但实际应该是
> Displays the application component for the active URL. Manages navigation from one component to the next.

[源代码](https://github.com/angular/angular-cn/blob/46ea47d1261dd7315b5a79c578d4d4fbba9b0c90/public/docs/ts/latest/guide/router.jade#L340)看着没问题，不太清楚什么造成的。

**Comment by asnowwolf** [comment]
jade中多了一个空格导致的，已解决。
