### ISSUE TITLE
cookbook不应翻译为烹饪宝典

### ISSUE THREAD

**Issue by li-boxuan** [angular/angular-cn#320]
出错的URL：https://angular.cn/guide/visual-studio-2015

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

`本烹饪宝典介绍了`

建议的修改方式（可选）：

原文为cookbook，中文网站直译成“烹饪宝典”。熟悉英文的开发者一般知道cookbook是个比喻，cookbook = recipes = 技巧/集锦/宝典/攻略，而无英文基础的中文开发者则会摸不着头脑，不知道“烹饪宝典”的”烹饪“从何而来。建议去掉”烹饪“二字，仅保留”宝典“。

**Comment by asnowwolf** [comment]
这个当初翻译的时候也比较纠结。因为最初的版本把里面的每篇文章称作：recipe（菜谱、处方、秘诀），目录又叫做 cookbook，这确实是个比喻，不过中文中也有这种比喻，比如《鸟哥的Linux私房菜》，所以就直接译作烹饪宝典了。现在原文文章中不怎么提 recipe 了，也可以考虑改名，不过还没想好怎么译。从目前看，原文也取消了专门的 cookbook 分类，我打算直接译为本文、本章等，不再管它的遗留问题，你觉得如何？

**Comment by li-boxuan** [comment]
> 原文也取消了专门的 cookbook 分类，我打算直接译为本文、本章等，不再管它的遗留问题

LGTM 👍
