### ISSUE TITLE
tutorial toh-pt4

### ISSUE THREAD

**Issue by liuz430524** [angular/angular-cn#322]
出错的URL：
[https://www.angular.cn/tutorial/toh-pt4#call-it-in-codengoninitcode](https://www.angular.cn/tutorial/toh-pt4#call-it-in-codengoninitcode)

错误的内容：
你应该改为在 ngOnInit 生命周期钩子中调用 getHeroes()，并且等 Angular 构造出 HeroesComponent 的实例之后，找个恰当的时机调用 ngOnInit。

建议的修改方式：
... 而是选择让 getHeroes() 在 ngOnInit 生命周期钩子中被调用，之后交由 Angular 处理，它会在构造出 HeroesComponent 的实例之后的某个合适的时刻调用 ngOnInit。

说明：
语义错误。翻译的句子中主语是”你“，导致语义变成”你...找个恰当的时机调用 ngOnInit“，很显然原文是 let Angular call ngOnInit。可能会让读者误解。建议的修改比较意译，供参考。

**Comment by asnowwolf** [comment]
恩，可以，谢谢，我喜欢意译。
