### ISSUE TITLE
A tiny typo

### ISSUE THREAD

**Issue by hll1682003** [angular/angular-cn#323]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

https://angular.cn/guide/template-syntax#emeventem-and-event-handling-statements

中文文本：“上面的代码在把输入框的 value 属性绑定到 firstName 属性。”
英文原文：“This code sets the input box value property by binding to the name property. ”

建议的修改方式（可选）：

中文应该是改成“绑定到name属性”，而不是“绑定到firstName属性”。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

hll1682003

感谢您的贡献。

**Comment by asnowwolf** [comment]
谢谢，已经被其他人的 PR 修正了。
