### ISSUE TITLE
“国际化（i18n）”的文本显示成了源代码？

### ISSUE THREAD

**Issue by ivandova** [angular/angular-cn#327]
出错的URL：
https://angular.cn/guide/i18n#set-a-custom-id-for-persistence-and-maintenance

这一章之后的所有文字貌似都按源代码显示了。

**Comment by asnowwolf** [comment]
无法重现此问题，强制刷新一下试试？

**Comment by ivandova** [comment]
试过“Empty cache and hard reload", 还是一样：
![image](https://user-images.githubusercontent.com/1582293/44505016-57c2bd00-a6e2-11e8-9088-c3e44afb57c8.png)

**Comment by asnowwolf** [comment]
看到了，已修。等下 cdn 更新。

**Comment by asnowwolf** [comment]
刷新好了，你验证通过就关闭这个 issue。多谢。

**Comment by ivandova** [comment]
谢谢修复！
