### ISSUE TITLE
路由与导航章节一些还没翻译

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular-cn#33]
https://angular.cn/docs/ts/latest/guide/router.html

这部分还没翻译：

> Technically, pathMatch = 'full' results in a route hit when the remaining, unmatched segments of the URL match ''. In our example, the redirect is at the top level of the route configuration tree so the remaining URL and the entire URL are the same thing.
> 
> The other possible pathMatch value is 'prefix' which tells the router to match the redirect route when the remaining URL begins with the redirect route's prefix path.
> 
> That's not what we want to do here. If the pathMatch value were 'prefix', every URL would match ''. We could never navigate to /crisis-center/1 because the redirect route would match first and send us to the CrisisListComponent.
> 
> We should redirect to the CrisisListComponent only when the entire (remaining) url is ''.
> 
> Learn more in Victor Savkin's blog post on redirects.

**Comment by asnowwolf** [comment]
已解决
