### ISSUE TITLE
NgModule中API翻译出错

### ISSUE THREAD

**Issue by fenglanzhan** [angular/angular-cn#343]
出错的URL：https://angular.cn/api/core/NgModule

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
属性表格中，jit选项说明翻译出错。
建议的修改方式（可选）：
根据英文原文：“If true, this module will be skipped by the AOT compiler and so will always be compiled using JIT.”，  
应该翻译为“ 如果为 true，则该模块将会被 AOT 编译器忽略，因此始终会使用JIT编译”，而不是“永远不会用 JIT 编译它”

**Comment by asnowwolf** [comment]
已改正。
