### ISSUE TITLE
https://angular.cn/api/forms/FormControlName 多打了‘使用’俩字

### ISSUE THREAD

**Issue by finley-fuelx** [angular/angular-cn#353]
多打了使用俩字

出错的URL：https://angular.cn/api/forms/FormControlName

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
从 Angular v6 开始，已经废弃了在响应式表单中**使用使用**输入属性 ngModel 和事件 ngModelChange 的方式，并将在 Angular v7 中移除。

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：mafeifan

**Comment by asnowwolf** [comment]
已解决。
