### ISSUE TITLE
中文教程的代码框内容好像挂了

### ISSUE THREAD

**Issue by whforit** [angular/angular-cn#36]
heroes教程《英雄指南》中的代码框内容，显示不出。
以 `app/heroes.component.ts (showing renamings only)`为例：
显示：
`出错的文件: ../../../_fragments/toh-5/ts/app/heroes.component-heroes-component-renaming.ts.md   所在路径: docs,ts,latest,tutorial,toh-pt5 文档路径: ../../../`

**Comment by asnowwolf** [comment]
编译环境的问题，已解决，谢谢！
