### ISSUE TITLE
风格指南 中英文对应问题

### ISSUE THREAD

**Issue by hhelibeb** [angular/angular-cn#366]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/guide/styleguide#%E6%8C%87%E4%BB%A4%E9%80%89%E6%8B%A9%E5%99%A8

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

中文：指令选择器
英文：Component selectors

中文：风格 02-06
英文：Style 05-02

中文：为何？Angular HTML 解析器是大小写敏感的，它识别小写驼峰写法。
英文：Why? Keeps the element names consistent with the specification for Custom Elements.

建议的修改方式（可选）：

按下文Directive selectors才是指令选择器，此处疑是中英文文本对应出错。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
是版本同步时的失误，已改正。
