### ISSUE TITLE
链接url错误

### ISSUE THREAD

**Issue by dabaii** [angular/angular-cn#374]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://www.angular.cn/guide/architecture-components#pipes

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
Angular 自带了很多管道，比如 date 管道和 Pipes API 列表 管道，完整的列表参见 。你也可以自己定义一些新管道。

建议的修改方式（可选）：
Pipes API 超链接错误. 目前使用的是:
https://angular.cno/api/common/CurrencyPipe
域名cn后面多了一个o,导致链接无法跳转.正确链接应更了是:
https://angular.cn/api/common/CurrencyPipe
 

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：大白

**Comment by asnowwolf** [comment]
已解决
