### ISSUE TITLE
可能是渲染出错的小问题

### ISSUE THREAD

**Issue by hcfw007** [angular/angular-cn#376]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：
https://angular.cn/tutorial/toh-pt5#heroescomponent-hero-links

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
如图所示，在这一段描述location作用的说明中出现了文字缺失和错位的情况
![chrome](https://user-images.githubusercontent.com/13669999/51600105-350c2d00-1f3c-11e9-8929-5068265c67ed.png)
看了一眼你们相关的md文件，发现原文是正常的，怀疑是渲染过程中出的问题。
![toh-p5 md](https://user-images.githubusercontent.com/13669999/51600110-35a4c380-1f3c-11e9-942c-ac546e354094.png)

建议的修改方式（可选）：
如果我找到了我会来补上的...

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
恩，多谢，是对照翻译代码的问题，已经解决了。
