### ISSUE TITLE
服务端渲染翻译错误

### ISSUE THREAD

**Issue by diankourenxia** [angular/angular-cn#382]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/guide/universal#creating-scripts

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：现在，来创建一些便利脚本，在以后帮助我们完成这些琐事。 你可以在 Angular 配置文件 angular.json 的 "server" 区添加这些脚本。

建议的修改方式（可选）：

现在，来创建一些便利脚本，在以后帮助我们完成这些琐事。 你可以在 package.json 的 "script" 区添加这些脚本。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：hugh

**Comment by asnowwolf** [comment]
哦，谢谢，这是因为文档尚未同步到最新版本导致的，等我有空了就同步一下。

**Comment by diankourenxia** [comment]
辛苦~

**Comment by asnowwolf** [comment]
已经同步完毕，验证后请关闭。
