### ISSUE TITLE
网站404了

### ISSUE THREAD

**Issue by loveholly** [angular/angular-cn#383]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
解决 #377 导致的衍生 bug，已解决，多谢提醒。

**Comment by loveholly** [comment]
辛苦了

**Comment by asnowwolf** [comment]
如果你那里验证了，就关闭这个 issue。
