### ISSUE TITLE
中文文档中代码片段有错误

### ISSUE THREAD

**Issue by luver225** [angular/angular-cn#393]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://www.angular.cn/guide/template-syntax

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
文档--核心语法--组件与模板--模板语法--表达式上下文：
`<input #customerInput>{{customerInput.value}}</label>`

建议的修改方式（可选）：
语法错误，英文版中对应的是：
`<label>Type something:
  <input #customerInput>{{customerInput.value}}
</label>`

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：luver225

**Comment by asnowwolf** [comment]
这应该是版本差异导致的，我这是同步的 master 分支，目前的版本是 8.0.0 beta.4

**Comment by luver225** [comment]
你好，我不太明白版本管控问题，我只是知道现在中文文档上有这个错误。那应该怎么处理呢...

**Comment by asnowwolf** [comment]
只要等英文版也同步到这个版本就可以了。不用改。你可以看看英文版的 8.0.0-beta.4 是否跟这个一样。

**Comment by luver225** [comment]
首先，这应该是语法错误，然后我看了英文版的 8.0.0-beta.8 （https://next.angular.io/guide/template-syntax），其代码片段如下：
<label>Type something:
  <input #customerInput>{{customerInput.value}}
</label>
所以，我理解是中文版的 8.0.0 beta.4 在这里写错了。

**Comment by luver225** [comment]
首先，这应该是语法错误，然后我看了英文版的 8.0.0-beta.8 （https://next.angular.io/guide/template-syntax），其代码片段如下：
`<label>Type something:
  <input #customerInput>{{customerInput.value}}
</label>`
所以，我理解是中文版的 8.0.0 beta.4 在这里写错了？

**Comment by asnowwolf** [comment]
哦，看样子确实是翻译时出错了，我回头查查源码，多谢指出！

**Comment by asnowwolf** [comment]
检查过了，这个错误是 beta.4 的英文版就存在的。等将来同步到 beta.8 应该就解决了。

**Comment by luver225** [comment]
ok
