### ISSUE TITLE
关于花括号的疑问

### ISSUE THREAD

**Issue by tianyu94** [angular/angular-cn#394]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

## 出错的URL：
[https://angular.cn/guide/displaying-data](https://angular.cn/guide/displaying-data)

## 错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
...
接着，修改模板。 现在它显示的是英雄的 id 和 name。 要修复它，只显示英雄的 name 属性就行了。
src/app/app.component.ts (template)
```
template: `
  <h1>{{title}}</h1>
  <h2>My favorite hero is: {{myHero.name}}</h2>
  <p>Heroes:</p>
  <ul>
    <li *ngFor="let hero of heroes">
      {{ hero.name }} <-- (就是有个疑问，这种插值表达式是统一加空格还是不加空格呢？虽然我看官网的也是这样的（强迫症犯了😄）)
    </li>
  </ul>
`
```
...

## 建议的修改方式（可选）：

是否需要统一，需要的话我之后在学习过程中顺便就把他们改了

**Comment by asnowwolf** [comment]
这些范例代码都是直接来自英文版的，中文版不作任何修改。我支持统一格式，不过你最好给英文版发 PR，这样我下次同步时就会生效了。

**Comment by tianyu94** [comment]
got it~
