### ISSUE TITLE
为什么angular.cn官网的翻译和项目里的不一样呢？

### ISSUE THREAD

**Issue by tianyu94** [angular/angular-cn#395]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

## 出错的URL：
https://angular.cn/guide/template-syntax

## 错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

**官网的：**

> 非常简单
> 虽然也可以写复杂的模板表达式，不过最好避免那样做。
> 
> 属性名或方法调用应该是常态，但偶然使用逻辑取反 ! 也是可以的。 其它情况下，应该把应用程序和业务逻辑限制在组件中，这样它才能更容易开发和测试。

**项目里的：**

```
#### 非常简单

Although it's possible to write quite complex template expressions, you should avoid them.

虽然也可以写出相当复杂的模板表达式，但不要那么写。

A property name or method call should be the norm.
An occasional Boolean negation (`!`) is OK.
Otherwise, confine application and business logic to the component itself,
where it will be easier to develop and test.

常规是属性名或方法调用。偶尔的逻辑取反 (`!`) 也还凑合。
其它情况下，应在组件中实现应用和业务逻辑，使开发和测试变得更容易。
```

**Comment by asnowwolf** [comment]
你看的可能是 master 分支？现在的最新版本在 aio 分支下，master 分支是 angular v2 的。

**Comment by tianyu94** [comment]
刚才确认了下，是在aio分支的

**Comment by asnowwolf** [comment]
应该是没有从预览库同步到正式库导致的，现在应该可以了。

**Comment by tianyu94** [comment]
thx~
