### ISSUE TITLE
文档中 angular 版本和官方显示不一致，stable版本目前是 v7.2.10 ，但是 angular.cn 显示是 v8.0.0-beta.4

### ISSUE THREAD

**Issue by xiao-po** [angular/angular-cn#398]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/generated/navigation.json

### 官网
> __versionInfo.version : 7.2.11-local

### angular.cn

__versionInfo.version : 8.0.0-build.97

请问为什么会有这种差异，官方并没有 8 版本下的 stable 版本，而文档的 navigation 下方是 `stable (v8.0.0-beta.4) ` ，希望查清楚一下。

而且假设有 8 版本的文档，angular.cn 中也没有 7 的列表，只有 8-beta, v6, v5, v4, v2

**Comment by asnowwolf** [comment]
这是直接从 master 分支同步的，这个版本号是从 angular/angular 库自动获取的，我没有动过它。

**Comment by xiao-po** [comment]
@asnowwolf  我稍微跟踪了下，angular/angular 下面有一份 navigation.json 的文件，但是那份文件中并没有 __versionInfo 的字段，我认为是自动生成的。

然后我看了下 angular/angular 下 master 分支，package.json 写的 version 是 v8.0.0-beta.9，而 7.2.x 分支下是 v7.2.10。

官方没有写 stable 分支，的确有点失误。 但是我看了下 angular/angular 的 release，7.2.x 和 8-beta 两个版本是交替 release 的，是否只需要同步来自 release 的 7.2.x 所处的 commit 就行了呢？我这么猜测一下

**Comment by asnowwolf** [comment]
其实没啥必要，现在 ng 的兼容性很高，拿新版本的文档套用到旧版本并不会有什么负面影响，反倒可以让大家更早接触新版本的 API。实际上文档本身并没有分叉，7.x 和 8.x 之间的文档部分并没有差异，只是 API 略有差异，但是不太值得为此专门开不同的文档站。

**Comment by xiao-po** [comment]
我并没有说要开专门的文档站，但是作为中文站，这种版本上的错误不应该出现，我只是想修复下这个来自编译所产生的版本错误。

毕竟现在官方也没有 8 的文档，我今天看文档的时候误以为 8 已经 stable 了，结果一看并没有。

**Comment by asnowwolf** [comment]
哦，明白了，我研究下。

**Comment by krwu** [comment]
今天看到中文网的 stable (v8.0.0-beta.4)  产生了同样的疑惑，过来一看，原来已经有人提过了。

**Comment by sz274071580** [comment]
我使用angular6，在用到HttpClient发送请求时，发现参数中带有"+"字符，该参数无法传递到服务端，通常在浏览器中会自动将"+"转义成"%2B"而，angular的HttpClient并没有对"+"转义，应该怎么解决呢？

**Comment by asnowwolf** [comment]
@sz274071580 请单开 issue。

**Comment by asnowwolf** [comment]
这是因为生成版本号时读取了 angular-src 的 package.json，已解决。
