### ISSUE TITLE
多谢你们，不过好像有些翻译的生硬

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular-cn#4]
似乎有一些地方方言，  比如  【包儿文件 】

**Comment by iloveyo123u1** [comment]
http://www.angular.live/docs/ts/latest/guide/webpack.html

我们并不需要很多配置来运行单元测试。 我们不需要在开发环境和产品环境下引入的那些加载器和插件。 我们可能还不需要在单元测试中加载和处理css文件，如果那么做就会拖慢我们的速度；所以我们用一个null加载器来处理所有CSS




比如有这样一段
用了好多个我们，感觉翻译有点像机器翻译 


最后总的来说，翻译质量是非常高的，感谢你们的付出

**Comment by asnowwolf** [comment]
谢谢！这篇还没做二校，不过我们会全文档搜一下，批量处理一下。

**Comment by iloveyo123u1** [comment]
非常的感谢

**Comment by asnowwolf** [comment]
已经初步改了一下，已经发布了新版，请检查。被接受的issue，其提出者都可以在鸣谢清单中署名，你想署什么名字？

**Comment by asnowwolf** [comment]
另外，包儿文件不算方言，只是比较口语化一点。我再斟酌一下

**Comment by Elderry** [comment]
同样先献上感谢，在网络环境不太好的地方中文版比原版打开要流畅。
另外以我个人意见，儿化音在这样一篇官方文档的翻译中并不合适，猜测译者是北京人？我可以理解在你们看来是口语，但对于不习惯的人看上去确实是方言了。

**Comment by asnowwolf** [comment]
不是北京人，不过是北方人。
你说的有道理，接下来准备改了。

**Comment by asnowwolf** [comment]
去掉了大部分儿化音，只保留了“一会儿”的说法
