### ISSUE TITLE
生命周期钩子有两个错别字

### ISSUE THREAD

**Issue by ChaoQunPeng** [angular/angular-cn#406]
> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：
https://angular.cn/guide/lifecycle-hooks#component-lifecycle-hooks-overview

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
![image](https://user-images.githubusercontent.com/23206231/57079692-75412f80-6d23-11e9-95c8-4393f8d5c4a4.png)

建议的修改方式（可选）：应该是每当吧

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
已解决。
