### ISSUE TITLE
如何查看Angular 6.x的中文文档

### ISSUE THREAD

**Issue by wushanchao** [angular/angular-cn#418]
看项目历史有两三年了，应该有Angular 6.x的中文文档。
但是项目分支上看不到相关。

**Comment by asnowwolf** [comment]
有 6.x 版本，但是没有专门打标签，因为从 4.0 到 8.0 都可以用一套文档，结合看 change log 了解下 breaking changes 就可以了。在日常开发中不用特别关心它们的差异。
