### ISSUE TITLE
chrome 浏览器中 “安装 Angular” 功能

### ISSUE THREAD

**Issue by dancci** [angular/angular-cn#422]
我在用 chrome 浏览器查看 angular.cn 网站时，浏览器的菜单里会多出一个 “安装 Angular...” 功能。
其它的网站上没见过，请问这个功能是如何出现的？？？

**Comment by asnowwolf** [comment]
哪个版本的浏览器？抓个图我看一下……我这里没看到这个菜单。不过这个功能应该是属于 PWA 支持的一部分。Angular 官方文档早就实现了 PWA，而 PWA 的特征之一就是可安装。

**Comment by dancci** [comment]
![屏幕截图(7)](https://user-images.githubusercontent.com/6086151/62001962-dfece600-b12d-11e9-8a05-20ed21fdba53.png)
![屏幕截图(8)](https://user-images.githubusercontent.com/6086151/62001964-e0857c80-b12d-11e9-9346-93b0c0039063.png)
