### ISSUE TITLE
自己clone下来，跑起来样式不对

### ISSUE THREAD

**Issue by githubcheng2978** [angular/angular-cn#423]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
这里是预编译版本，你可以自己写一个 nginx.conf 来部署到本地。
https://github.com/ng-docs/ng-docs.github.io
