### ISSUE TITLE
英文与中文显示不一致

### ISSUE THREAD

**Issue by ghzjtian** [angular/angular-cn#424]
在 [https://angular.cn/guide/forms#create-the-hero-model-class](https://angular.cn/guide/forms#create-the-hero-model-class) 中的一个小错误  component 翻译为了 class.

![Snip20190729_1](https://user-images.githubusercontent.com/8456939/62027271-d5a31880-b20f-11e9-81bd-bdae916aaf84.png)

**Comment by leemove** [comment]
可以关了,已经改好了.

**Comment by asnowwolf** [comment]
多谢指出！
