### ISSUE TITLE
教程->服务中的几处翻译问题

### ISSUE THREAD

**Issue by kapr1k0rn** [angular/angular-cn#43]
1. 

> The consumer of our service doesn't know how the service gets the data. Our HeroService could get Hero data from anywhere. It could get the data from a web service or local storage or from a mock data source.

> **消费者**并不知道本服务会如何获取数据。 我们的 HeroService 服务可以从任何地方获取英雄的数据。 它可以从网络服务器获取，可以从浏览器的局部存储区获取，也可以是直接写在源码中的 mock 数据。

此处**消费者**建议改为**数据使用者**。

2. 

> That's the beauty of removing data access from the component. We can change our minds about the implementation as often as we like, for whatever reason, without touching any of the components that need heroes.

>**我们从组件中成功移除了数据访问代码，干得漂亮。** 这下子，我们可以随时改变数据访问的实现方式了。

这句话的翻译显然有误，不看原文会感觉一头雾水。建议改为：
>这就是从组件中移除数据访问代码的美妙之处。这样我们可以随时改变数据访问的实现方式，而无需对使用英雄的组件作任何改动。

3.
>We're ready to use the HeroService in other components starting with our AppComponent.

>我们已经在包括 AppComponent 在内的多个组件中使用了 HeroService 服务。 

此处应为
>我们可以在多个组件中使用HeroService服务了，先从AppComponent开始。

**Comment by asnowwolf** [comment]
改动比较多，发个PR吧，我回头merge一下，也好把你列入contributors。

**Comment by asnowwolf** [comment]
看得很细！赞！

**Comment by kapr1k0rn** [comment]
ok
