### ISSUE TITLE
路由与导航有一段示例代码有问题

### ISSUE THREAD

**Issue by edtim8** [angular/angular-cn#44]
中文版本显示和英文版本不同，angular.io是对的。见图

![capture5](https://cloud.githubusercontent.com/assets/7846368/17267557/e7fca742-563e-11e6-993d-c31caf4ed3d4.JPG)
![capture6](https://cloud.githubusercontent.com/assets/7846368/17267564/01e2a3be-563f-11e6-8020-5f228605d91d.JPG)

**Comment by asnowwolf** [comment]
已改正，谢谢指出
