### ISSUE TITLE
站点路由错误

### ISSUE THREAD

**Issue by timeswind** [angular/angular-cn#453]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/translations/cn/about
（任何除了https://angular.cn/ 的URL）

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

通过先进入主页再路由到文档各个位置都正常
但当直接进入非根目录（非主页）页面显示
RESOURCE NOT FOUND
We're sorry. The resource you are looking for cannot be found.

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by unnhao** [comment]
Has it been fixed? I can access it.

**Comment by timeswind** [comment]
> Has it been fixed? I can access it.

I tried on Chrome and Safari by pasting the URL(https://angular.cn/translations/cn/about), it still routes to the "Page Not Found" route

**Comment by asnowwolf** [comment]
我已重现了，正在查。@unnhao 可能是因为你的 PWA 缓存还在，开个隐身窗口就能重现
