### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by tony7sama** [angular/angular-cn#462]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：https://angular.cn/guide/singleton-services

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
Angular 创建惰性加载模块时会给它一个自己的注入器，它是根注入器的子注入器。 @SkipSelf() 让 Angular 在其父注入器中查找 **CoreModule**，

Angular creates a lazy loaded module with its own injector, a child of the root injector. @SkipSelf() causes Angular to look for a **GreetingModule** in the parent injector,

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
已改正，谢谢！下次发布时生效。
