### ISSUE TITLE
建议全文档【服务提供商】替换为【服务提供者】

### ISSUE THREAD

**Issue by sphawkcn** [angular/angular-cn#466]
出错的URL：https://angular.cn/start/data
出错的URL：https://angular.cn/guide/architecture

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

示例1：Angular 的 HttpClientModule 中注册了在整个应用中使用 HttpClient 服务的单个实例所需的服务提供商。

示例2：组件使用服务。服务会提供那些与视图不直接相关的功能。服务提供商可以作为依赖被注入到组件中， 这能让你的代码更加模块化、更加可复用、更加高效。

建议的修改方式（可选）：

建议全文档【服务提供商】替换为【服务提供者】

【服务提供商】在大脑中第一意识很容易与【商人】、【商业公司】等等商业化名词联系起来。而这里显然没有这个意思，建议这里不要翻译得这么具象，建议使用【服务提供者】这种比较泛化的名词。

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
这个当初也讨论过，之所以选择提供商这个译法，主要有两个原因：

1. ISP: Internet Service Provider：互联网服务提供商
2. Provider 就是更泛化的 Factory，而 Factory 译作工厂，因此 Provider 也译作跟它平级的概念：提供商。

**Comment by sphawkcn** [comment]
1. ISP: Internet Service Provider：互联网服务提供商
这个翻译确实没错，因为 ISP 确实就是【商业】公司，是可以对应到现实生活中的公司的。
但是 Angular 的 Provider 是不能对应到现实中的商业公司的。


2. Provider 就是更泛化的 Factory，而 Factory 译作工厂，因此 Provider 也译作跟它平级的概念：提供商。
Factory 本义是工厂，但是是否译作工厂，还是要看具体的语境，有时候，要译作产出者、制造方。

个人觉得哪个单词译作哪个汉语词汇，需要根据具体的语境来变化。当然，这也只是我个人的看法，不一定正确，你们当初也讨论过，说明你们也是考虑得很仔细的，无论翻译成什么，我也都是支持的，只是我初看文档的时候，【服务提供商】这个名词确实让我大脑卡顿了，所以就想是否可以有一个更贴近 Angular 中的语境的翻译。

**Comment by wabzsy** [comment]
+1

**Comment by asnowwolf** [comment]
我再想想，也调查下其他人的看法。

**Comment by asnowwolf** [comment]
已改，多谢两位的反馈。
