### ISSUE TITLE
[建议] api参考手册部分

### ISSUE THREAD

**Issue by qq83387856** [angular/angular-cn#47]
![image](https://cloud.githubusercontent.com/assets/12625278/17538812/738f0ea4-5edb-11e6-8c7d-3b50c4e58169.png)
考虑到最终版发布之后api状态应该都是稳定版，所以最终版本发布以后可以选择将状态隐藏。
因为现在没有发正式版本之前，想要查看api的状态还要点进去比较麻烦。

**Comment by asnowwolf** [comment]
官方文档组计划用angular 2重写docs，我先反映给他们，等新版docs框架推出后再改
