### ISSUE TITLE
angular2怎么做app

### ISSUE THREAD

**Issue by MeiYuanChen** [angular/angular-cn#48]
看了看文档目录好像没有提到怎么制作app，只提到怎么制作web。
特性 中所指的制作app 是指使用ionic2这款框架吗？

**Comment by asnowwolf** [comment]
制作app方面没有任何限制，实际上大多数的页面都能直接做成app —— 把它们扔进cordova就好了。

**Comment by ibufu** [comment]
@MeiYuanChen 可以搜一下native script

**Comment by asnowwolf** [comment]
这不是核心内容，只是一个应用场景。所以目前没有包含，短期内应该也没有计划。
如果想做原生应用，可以搜NativeScript，同时它也能结合reactnative。
如果要做hybrid应用，可以搜一下ionic，它的2.0是基于ng2的，不过还没有release

2016年8月10日 下午5:26，"MeiYuanChen" <notifications@github.com>写道：
