### ISSUE TITLE
教程-英雄编辑器-双向绑定 节的翻译有遗漏

### ISSUE THREAD

**Issue by ewen80** [angular/angular-cn#49]
原教程中有一段：
Before we can use two-way data binding for form inputs, we need to import the FormsModule package in our Angular module. We add it to the NgModule decorator's imports array. This array contains the list of external modules used by our application. Now we have included the forms package which includes ngModel.

中文版中没有，如果少了这段，程序执行会出错。

**Comment by rexebin** [comment]
谢谢。检查了，已经添加。

@ewen80 请问程序执行出错是什么意思？
