### ISSUE TITLE
cn官网 现在版本是8.10？貌似之前还更新到10了，出什么问题了？

### ISSUE THREAD

**Issue by aohan237** [angular/angular-cn#493]
> 注意：新版本文档位于aio分支下，master分支下是老版本的文档。

> 对于错别字或明显的语法错误，建议直接发 PR（在content目录下相应的文件上直接编辑，保存时就会自动变成PR）。

出错的URL：

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：

建议的修改方式（可选）：

英雄留名（会出现在鸣谢清单中，默认使用你的github id）：

**Comment by asnowwolf** [comment]
我看了一下，是11.0 的版本啊，你再强刷验证下。因为开启了 PWA，所以如果你上次打开它的时候是 8.10，那么这次打开时就会先用 8.10 版本，同时后台下载最新版。

**Comment by aohan237** [comment]
果然是。
强刷新倒是没问题，我开了几次网页都发现是8.10，还以为angularcn凉了。
感觉这个pwa还是有点问题。
首先我有网络连接，第一件事不应该是先检查版本？如果发现有新版本，直接强制用新版本才对？

**Comment by aohan237** [comment]
有个小问题，文档能不能出个导出epub，离线阅读
