### ISSUE TITLE
中英文混合时请在英文前后加上一个英文 Space

### ISSUE THREAD

**Issue by hantsy** [angular/angular-cn#5]
如：Angular指南
变更为： Angular 指南

十几前年，我翻译 Spring Live 的时候就发现中英文混合在 PDF 中十分别扭，当然在浏览器好一点。其实一些国内中文翻译时几乎约定加上一个空格。

**Comment by asnowwolf** [comment]
好，也有道理，我们评估一下看看。

**Comment by asnowwolf** [comment]
接受了。我们将把你加入鸣谢清单，你愿意署哪个名字？

**Comment by hantsy** [comment]
hantsy

**Comment by asnowwolf** [comment]
已解决，请验证。
