### ISSUE TITLE
快速上手部分，中文代码和英文代码不一样 - 没有Product interface

### ISSUE THREAD

**Issue by deqing** [angular/angular-cn#501]
出错的URL：
https://angular.cn/start

错误的内容（请拷贝进来一份精确的出错文本，以便我定位）：
> 要创建范例项目，请[在 StackBlitz 中生成一个预置的范例项目](https://angular.cn/generated/live-examples/getting-started-v0/stackblitz.html)

这个链接里的代码和英文版里的[代码](https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html)不一样。

product.ts里面少了这段：
```
export interface Product {
  id: number;
  name: string;
  price: number;
  description: string;
}
```
所以后面的例子找不到Product这个类

**Comment by asnowwolf** [comment]
不好意思，翻译的时候光顾内容了，没验证demo，同步v13的时候我顺便看看这个问题，估计是个系统性问题。
