### ISSUE TITLE
模板语法 - Attribute 绑定 章节错误

### ISSUE THREAD

**Issue by duxiaofeng-github** [angular/angular-cn#56]
> 正如消息中所说， <td> 元素没有 colspan Attribute 。 但是插值表达式和属性绑定只能设置 属性 ，而不是 Attribute 。
> 
> As the message says, the <td> element does not have a colspan property. It has the "colspan" attribute, but interpolation and property binding can set only properties, not attributes.

更正：正如消息中所说， <td> 元素没有 colspan Property 。他只有 colspan Attribute， 但是插值表达式和属性绑定只能设置 Property ，而不能设置 Attribute 。

不得不说这翻译看得我完全不知所措~~
然后不严谨的话，请不要用“由于我们对翻译质量的极端要求”这样的描述。

**Comment by rexebin** [comment]
多谢你的反馈。已经修正。

我们的确有这个承诺，也是本着这个承诺来做的。我们也是在不断的学习过程中，在早期翻译的工作中确实有很多不尽人意的地方，我们也计划抽空不断改进。

我们同时也期待社区能给我们带来更多的反馈，帮助我们完善文档的准确性。

再次感谢你的贡献！
