### ISSUE TITLE
纠错-（教程-5.服务）

### ISSUE THREAD

**Issue by XdCareWy** [angular/angular-cn#57]
> providers 数组告诉 Angular ，当它创建新的 AppComponent 组件时，也要创建一个 HeroService 的新实例。 AppComponent 会使用那个服务来**_获取影响列表_**，在它组件树中的每一个子组件也同样如此。

我对照下面的英文，这块应该是敲错了， service to get heroes

**Comment by rexebin** [comment]
谢谢！已修正。
