### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by hantsy** [angular/angular-cn#6]
应该是 开发人员指南
不是 开发指南

**Comment by asnowwolf** [comment]
开始时是翻译成开发人员指南的，不过太绕口了，后来就批量翻译成了开发指南。其实这两者在大多数语境中都是等价的。开发指南也必然是给开发人员用的。

**Comment by hantsy** [comment]
Developer Guide： 开发人员指南
API Reference： API 参考手册

我觉得【开发指南】， 【API 参考】 都比较生硬。

**Comment by asnowwolf** [comment]
API参考接受了，开发指南还是保留原样。
