### ISSUE TITLE
final2.0.0中文官网文档左侧目录问题

### ISSUE THREAD

**Issue by MuyNooB** [angular/angular-cn#69]
比如该页面https://angular.cn/docs/ts/latest/guide/ngmodule.html，左侧目录最下面Angular2 for Typescript会把一级目录的烹饪宝典覆盖掉，小bug，但还是中文网团队能够完善。
最后感谢团队让英文不好的人能早接触到这个最新的框架。

**Comment by rexebin** [comment]
官方正在解决此问题，谢谢。

**Comment by todoubaba** [comment]
已修正。
