### ISSUE TITLE
Angular 2词汇表 原文也错了

### ISSUE THREAD

**Issue by biolee** [angular/angular-cn#74]
https://angular.cn/docs/ts/latest/guide/glossary.html

每个 Angular 应用程序都有一个应用程序根模块类。按规约这个类的名字为 AppModule ，存放在名为 **app.component.ts** 的文件。
->
每个 Angular 应用程序都有一个应用程序根模块类。按规约这个类的名字为 AppModule ，存放在名为 **app.module.ts** 的文件。

**Comment by rexebin** [comment]
已修正，谢谢。
