### ISSUE TITLE
几个翻译问题

### ISSUE THREAD

**Issue by vaanxy** [angular/angular-cn#79]
1.高级文档－》Angular模块－》AppModule应用根模块 这一节中
@NgModel应改为@NgModule

2.高级文档－》Angular模块－》用路由器实现延迟（ Lazy ）加载－》路由到特性模块这1小节中
”目录中也有一个新文件 Contact.routing.ts“ 应该为“目录中也有一个新文件 contact.routing.ts”
之前的文档中提到过所有文件名应该小写，原文中也是全小写。

**Comment by asnowwolf** [comment]
已经改正。
