### ISSUE TITLE
属性型指令使用部分翻译错误

### ISSUE THREAD

**Issue by liuguichi** [angular/angular-cn#82]
We'll add an import statement to fetch the 'Highlight' directive and, added that class to the declarations NgModule metadata so that Angular will recognize our directive when it encounters myHighlight in the template.

我们添加了一个 import 语句来获得 'Highlight' 指令类，并把这个类添加到 AppComponent 组件的 directives 数组中。 这样，当 Angular 在模板中遇到 myHighlight 时，就能认出这是指令了。

你记着设置 @Component 的 directives 数组了吗？它很容易被忘掉。

Did you remember to add the directive to the the declarations attribute of @NgModule? It is easy to forget!

以上都是declarations 数组才对

https://angular.cn/docs/ts/latest/guide/attribute-directives.html#!#write-directive

**Comment by asnowwolf** [comment]
已改正
