### ISSUE TITLE
教程7 import angular-in-memory-web-api 错误

### ISSUE THREAD

**Issue by n37r06u3** [angular/angular-cn#84]
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';

改为

import { InMemoryWebApiModule } from 'angular2-in-memory-web-api';

原因
package.json里依赖的是
"angular2-in-memory-web-api": "0.0.20"

**Comment by asnowwolf** [comment]
https://www.npmjs.com/package/angular-in-memory-web-api

>As of v.0.1.0, the npm package was renamed from angular2-in-memory-web-api to its current name, angular-in-memory-web-api

所以不带2的才是最新的，是package.json需要改。已改正。

**Comment by rdmclin2** [comment]
赞👍
