### ISSUE TITLE
部分样式出错, 导致英文直接出现

### ISSUE THREAD

**Issue by xinshangshangxin** [angular/angular-cn#86]
[https://angular.cn/docs/ts/latest/tutorial/toh-pt5.html](https://angular.cn/docs/ts/latest/tutorial/toh-pt5.html)

`Set the component metadata's templateUrl and styleUrls properties to refer to both files.`
未点击下直接出现英文, 实际为下面第5条的内容, 同时第4条未翻译(虽然能看懂....)

![image](https://cloud.githubusercontent.com/assets/8779091/19031818/e510c734-8988-11e6-825b-22aa78d13432.png)

**Comment by rexebin** [comment]
谢谢！已经修复。
