### ISSUE TITLE
测试一章中的目录导航显示英文时会导致后面的序号顺延增加1

### ISSUE THREAD

**Issue by SangKa** [angular/angular-cn#93]
由于本章目录导航是带序号的，点击任意标题行时(无论是主标题还是副标题)都会增加一行，导致下面的标题需要顺延增加1

**Comment by rexebin** [comment]
这个问题暂时没有好的解决办法。

**Comment by rexebin** [comment]
已找到解决办法。多谢 @todoubaba !

我们将逐步修正所有文章。
