### ISSUE TITLE
官方文档已经更新到2.1，有些文档有变更

### ISSUE THREAD

**Issue by SoaringTiger** [angular/angular-cn#94]
比如：
https://angular.cn/docs/ts/latest/api/forms/index/FormArrayName-directive.html
例子中 get cities(): FormArray { return this.form.get('cities'); }

而官方文档
https://angular.io/docs/ts/latest/api/forms/index/FormArrayName-directive.html
已改为  get cities(): FormArray { return this.form.get('cities') as FormArray;  }

**Comment by asnowwolf** [comment]
已经升级到了最新版
