### ISSUE TITLE
英雄指南路由翻译bug2

### ISSUE THREAD

**Issue by mannyzhuo** [angular/angular-cn#97]
![image](https://cloud.githubusercontent.com/assets/13795608/19504477/1db255e2-95ed-11e6-8217-1cf93f00f78e.png)

![image](https://cloud.githubusercontent.com/assets/13795608/19513617/1c3f4dec-9623-11e6-98c7-500d5f6adf6f.png)

**Comment by rexebin** [comment]
谢谢
